cncf/glossary

- .github/settings.yml
Signed-off-by: Chris Aniszczyk <caniszczyk@gmail.com>
> Add Cathy as a maintainer

- CONTRIBUTING.md
Based on the State-of-the-Edge doc as suggested by Chris. @JasonMorgan @idealusrname, let me know what you think.
> Adding "contributing" doc

- .github/settings.yml
Also changed Catherine to a maintainer and put a link to github's settings bot docs.
> Added Michael as a maintainer.

- definitions/container.md
> Issue #17 Container Definition

- definitions/auto_scaling.md
- definitions/continuous_delivery.yaml
Solves #14.
Thoughts on Autoscaling vs. Auto Scaling?
Personally leaning towards Autoscaling due to K8s usage.
> added autoscaling definition. removed access yaml

- definitions/stateless_apps.md
- definitions/tightly_coupled_architectures.md
Solves Issues #23 and #22
As directed by @JasonMorgan , I've filled in the definitions of Tightly Coupled Architecture and Stateless Applications in their respective files.
> Tightly Coupled Architectures & Stateless Apps Definition filled

- definitions/distributed_systems.md
- definitions/portability.md
Solves issues #20 and #21 .
As directed by @CathPag , added the "How it Helps" section in the Distributed Systems definition in its respective file. 
As requested by @JasonMorgan , filled the definition for Portability in its respective file.
> Distributed Systems and Probability Definitions updated

- definitions/distributed_systems.md
@IdealUsrname @DanielJonesEB @JasonMorgan please approve and merge this entry
> Distributed system V1-ready

- definitions/immutable_infrastructure.md
@JasonMorgan @DanielJonesEB @IdealUsrname please review/approve/merge
> Immutable infrastructure V1-ready

- definitions/infrastructure_as_code.md
@IdealUsrname @JasonMorgan @DanielJonesEB, please review/approve/merge.
> IaC V1-ready

- definitions/kubernetes.md
@IdealUsrname @JasonMorgan @DanielJonesEB, please review/approve/merge.
> Kubernetes V1-ready

- README.md
Making our immediate needs and the project more visible. Addressed issue #151
> Added getting started section to readme.

- .github/settings.yml
Added murillodigital as a new maintainer for the repo.
> Adding new maintainer

- how-to.md
Fixed spelling mistake and grammatical errors on line 14 of https://github.com/cncf/glossary/blob/main/how-to.md
Before: 
- **Pull requests (PR):** once you created a pull request is should appear here (more to PRs below),
After:
- **Pull requests (PR):** once you have created a pull request, it should appear here (more to PRs below),
> Fixed spelling mistake and grammatical errors

- definitions/virtual_machine.md
I have not made a whole lot of changes to the previously written content although I have referred some of the complete definition and websites for the technical soundness of the statements but I still am a little confused if the definition and other things are up to the mark.
Also on the definition by **redHat organization** i came across a term **Hypervisor** which is not present in this project which but is an integral software for creating virtual machines so i think it would be nice if we could add it to glossary as well.
_Please let me know if i need to make any further changes to this same entity (i.e. virtual machines)._
> Updated Virtual Machines to New Format

- definitions/client_server_architecture.md
Please let us know what you think
> Client-server architecture V2

- definitions/tightly_coupled_architectures.md
-  Updated the entity to new format.
-   Checked the definition for typos/grammatical mistakes.
-   I have also asked some of my friends from Technical and Non-Technical backgrounds if they were able to understand the all the sections to which they responded positively.
I have not made a whole lot of changes to the previously written content although I have referred some of the complete 
definition and websites for the technical approach of the statements.
_Please let me know if i need to make any further changes to this same entity (i.e. Tightly Coupled Architectures)._
> Updated Tightly Coupled Architectures to New Format

- wordlist.txt
> Added Serverless

- definitions/portability.md
> Portability V2

- definitions/cloud_native_security.md
Changed the definition to make it simpler and remove some marketing speak.
> Updated Definition of Cloud Native Security

- definitions/distributed_apps.md
Updated to new format and adding links to related terms.
> Update distributed apps to v2 format

- definitions/loosely_coupled_architecture.md
* Linked back **Microservices** to the definition present in the Glossary. 
* If it's possible?? I can help you folks with doing the same(Linking back to the definitions ) with other definitions also in the 
Glossary
> Update loosely_coupled_architecture.md acc to Updated Style guide

- definitions/horizontal_scaling.md
> Horizontal Scaling definition

- definitions/nodes.md
> update nodes.md to new format

- wordlist.txt
Added the terms **_saas, SaaS, CRM_** to [wordlist](https://github.com/cncf/glossary/blob/main/wordlist.txt) which are present in definition of SaaS. Spellcheck CI check should pass for #207 after merging this PR.
> Update wordlist.txt for terms in definition of SaaS

- definitions/serverless.md
Update status of definition of serverless to completed according to feedback received in #180
> Update status of definition of serverless to completed

- definitions/distributed_apps.md
@JasonMorgan  I think this is ready to go. Let's review and merge today
> Distributed apps V2-ready?

- definitions/cloud_native_tech.md
Minor syntax changes.
Mark Completed.
> Finish off Cloud Native Tech

- definitions/zero_trust_architecture.md
@ChrisJBurns wrote a great definition. 
Mark as complete.
> Marked ZTA Complete

- definitions/paas.md
- wordlist.txt
@JasonMorgan did a few small edits before creating the PR
> PaaS for V2

- content/en/monolithic_apps.md
- New PR to resolve conflicts occurred in #228
- All the changes are included as suggested in review 0564c48
- Resolves #143
> Updated monolithic apps to new format

- content/en/stateful_apps.md
Looks like we never updated this to complete!
> Changed to completed

- LOCALIZATION.md
- Guide: Open an Issue to notify initiation of a new localization 
- Guide: Merge the localization branch into `main` branch
This PR is related with PR #277.
Would better to merge after PR #277.
> Update localization guideline regarding Dev branch

- .github/ISSUE_TEMPLATE/l10n-initiation.md
This issue template includes 
- Information for language and language code for l10n
- List of volunteers
- Next actions from maintainers
> Add issue template for new l10n initiation

- LOCALIZATION.md
Corrects some wording in LOCALIZATION.MD
> correct some wording

- content/en/cloud_computing.md
CAPEX is an acronym that people might not know. It would be better not to use lingo. Broke it into "money or resources."
> removing CAPEX

- .github/settings.yml
- Fix indentation which may lead settings app failure
- Change the homepage
> Update settings.yaml to fix validation error

- LOCALIZATION.md
This PR improves localization guide.
- Introduce two parts
- Initiate a new localization team
- Get involved in an existing localization team
- More examples
- Note regarding permission
- ...
> Improve localization guide

- content/en/TLS(Transport Layer Security).md
> Definition for TLS(Transport Layer Security).md

- content/en/data_center.md
Add proposal for a definition of data center (issue #280 )
> Create entry for "data center"

- content/en/abstraction.md
+ link to service definition 
+ explanation of what a consumer is
> [Update] Abstraction

- content/bn/abstraction.md
- content/bn/cloud_computing.md
- content/bn/cloud_native_tech.md
- content/bn/cluster.md
- content/bn/container.md
- content/bn/devops.md
Signed-off-by: Saber Imtiaz  saberimtiazmitul@gmail.com
This is an initial PR as may need some improvements!
Tracking issue: #410
> [bn] Updating titles

- .github/workflows/labeler.yml
Signed-off-by: shivam tyagi <shivamt.ug19.ec@nitp.ac.in>
This is a fix for
- #434
> Fix Auto Labeling action

- content/es/observability.md
Translation observability.md to Spanish. Related issue https://github.com/cncf/glossary/issues/409
> feat: add content es/observability

- i18n/en.toml
- layouts/partials/feedback.html
This PR is related with https://github.com/cncf/glossary/issues/470#issuecomment-1050450210 .
After this PR gets merged, I will open a PR that applies L10n of Feedback section to `dev-ko` branch. 😊
> I18n of feedback section

- content/ko/virtual_machine.md
> Update Korean virtual_machine.md

- content/pt-br/application_programming_interface.md
Reopening - same content as https://github.com/cncf/glossary/pull/273, but now with an organized tree/commits. Sorry for the confusion :sweat_smile: 
Signed-off-by: Jéssica Lins <jessicaalins@gmail.com>
> Add content/pt-br/application_programming_interface.md

- content/en/database_as_a_service.md
- wordlist.txt
Added a new term: Database as a Service (DBaaS)
Fixes: #340
> Add content/en/database as a service

- content/pt-br/blue_green_deployment.md
Reopening - same content as https://github.com/cncf/glossary/pull/274, but now with an organized tree/commits. Sorry for the confusion :sweat_smile: 
Signed-off-by: Jéssica Lins <jessicaalins@gmail.com>
> Add content/pt-br/blue_green_deployment.md

- content/en/contribute/_index.md
ref #559
Change the snapshot for issue template
> Update how to contribute with new issue template

- .github/settings.yml
- CODEOWNERS
After a team discussion, we decided to let Francesco be one of the approver
> update italian contents approvers

- content/en/horizontal_scaling.md
Signed-off-by: Dipankar Das <dipsonu10@hotmail.com>
> Missing link to Vertical Scaling

- content/pt-br/container.md
Add container definition localization to ptbr.
> Add content/pt-br/container.md

- content/pt-br/api_gateway.md
Adding new localization to api gateway
> Add content/pt-br/api_gateway.md

- content/en/kubernetes.md
Signed-off-by: Dipankar Das <dipsonu10@hotmail.com>
> Typo Changes from 'document' to 'manifest file'

- CODEOWNERS
- this PR is to remove merge conflicts in [https://github.com/cncf/glossary/pull/654](https://github.com/cncf/glossary/pull/654)
> [hi] updated CODEOWNERS march 29 2022

- content/pt-br/contribute/_index.md
- content/pt-br/style-guide/_index.md
Apply title case in:
* How to contribute page
* Style guide page
> Apply title case in config pages

- content/pt-br/_index.md
> [pt-BR] Add contributors names 

- content/en/contribute/_index.md
> fixed typo in en/content/contribute/_index.md

- content/it/managed_services.md
> add managed services localization

- content/en/continuous_deployment.md
Signed-off-by: Vrukshali <tvrukshali@gmail.com>
Renamed "continuous_delivery.md" file to "continuous_delivery&continuous_deployment.md"
Added more information about Continuous Deployment and also about Continuous Deployment vs Continuous Delivery.
> Add content/en/continuous_deployment.md

- content/en/container-image.md
**Done**
I think it was accidentally left out :)
> [en] Fix: missing parts of container-image.md

- content/es/.wordlist.txt
- content/es/load_balancer.md
Related the issue https://github.com/cncf/glossary/issues/609
> Es loadbalancer

- .github/settings.yml
- CODEOWNERS
We need more maintainers for Bengali Localization to keep the PRs checked .
> [bn] Need to add approvers for Bengali Localization

- CODEOWNERS
This PR is to apply CODEOWNERS updates (dev-bn approver) in main to dev-bn
Will remove possible merge conflicts as well.
> Apply CODEOWNERS updates in main to dev-bn

- content/bn/style-guide/_index.md
Signed-off-by: Shadman Rafy  rafyndc18@gmail.com
Localizes `content/bn/style-guide/_index.md ` to Bengali
This is an intial PR as may need some improvements!
Tracking issue: #410 #660
> [bn] Localize `content/bn/style-guide/_index.md `

- content/es/.wordlist.txt
- content/es/api_gateway.md
Based on issue #563 
Please do a review of this concepts:
API Gateway : Concentrador API
I did not see any style guide or glossary about this translation.
Regards.
> [ESP] add content/es/api_gateway.md

- content/es/.wordlist.txt
- content/es/agile_software_development.md
- content/es/bare_metal_machine.md
- content/es/cloud_computing.md
- content/es/devops.md
- content/es/style-guide/_index.md
- i18n/es.toml
> feat: add content es/bare_metal_machine

- content/ko/_index.md
- content/ko/cloud_computing.md
- content/ko/cloud_native_apps.md
- content/ko/cloud_native_tech.md
- content/ko/container.md
- content/ko/containerization.md
- content/ko/microservices.md
- content/ko/monolithic_apps.md
- content/ko/virtual_machine.md
- 갱신이 필요한 문서를 확인 및 수정하였습니다. (_index.md 만 수정 필요)
- 제목에 영문을 병기하였습니다.
> [ko] Update outdated contents in dev-ko and add title reference

- content/es/.wordlist.txt
- content/es/blue_green_deployment.md
> feat(glossary): blue green deployment

- content/ko/_index.md
ref https://github.com/cncf/glossary/issues/379 (Tracking Korean Localization Progress)
1. update index page up to date.
2. add Korean contributors to ack (named contributors are based on commits or reviews for Korean contents)
> [ko] Update index page with acknowledgement to Korean contributors

- content/de/api_gateway.md
Add german translation for API Gateway.
Solves #507
> Add german translation for API Gateway

- content/de/abstraction.md
issue: https://github.com/cncf/glossary/issues/505
> [de] Abstraction

- content/es/.wordlist.txt
- content/es/_index.md
- content/es/abstraction.md
- content/es/agile_software_development.md
- content/es/api_gateway.md
- content/es/bare_metal_machine.md
- content/es/blue_green_deployment.md
- content/es/cloud_computing.md
- content/es/contribute/_index.md
- content/es/devops.md
- content/es/infrastructure_as_code.md
- content/es/kubernetes.md
- content/es/load_balancer.md
- content/es/style-guide/_index.md
The index Spanish files are out of date, they don't have recognitions for contributors, as well as missing some images and new paragraphs. This PR updates the version of those files.
> chore: Update index spanish files

- content/en/_TEMPLATE.md
- content/en/auto_scaling.md
- content/en/continuous_delivery.md
- content/en/continuous_deployment.md
- content/en/continuous_integration.md
- content/en/horizontal_scaling.md
- content/en/vertical_scaling.md
Issue : Add "Related terms" section to template #792
> Update _TEMPLATE.md and update "please also refer to" section

- .github/ISSUE_TEMPLATE/new-term.yml
Add checklist to the issue template for new term,
> Update issue template for new term to include ideal term suggestion

- content/bn/_index.md
Signed off: Saber Imtiaz
This PR Might require changes
Tracking issue: #410
> [bn] Updating the contributors in the index file

- content/en/contribute/_index.md
- content/en/contributor-ladder/_index.md
- content/en/style-guide/_index.md
This is kind of a pilot PR for adopting semantic line breaks into the markdown files, which will make the review process easier.
After collecting feedbacks and eventually merging this PR, I will work on other markdown files as well. 😊
> Adopt semantic line breaks

- content/pt-br/TLS(Transport Layer Security).md
Add 
- content/pt-br/TLS(Transport Layer Security).md
> Add content/pt-br/TLS(Transport Layer Security).md

- content/zh-cn/_index.md
Refined some description of the zh home page
> [zh] optimize the description on home page

- content/bn/_index.md
Signed-off-by: Saber Imtiaz saberimtiazmitul@gmail.com
Updated the acknowledgements
Tracking issue : #410
> [bn] Updated the Acknowledgement

- README.md
This extra line gap made no difference to the README.md and was inconsistent with rest of the code.
Signed-off-by: Uday Mehtani <udaymehtani@gmail.com>
> Deleted an extra line gap

- layouts/partials/navbar-lang-selector.html
> Fix visualization bug in navbar-lang-selector

- content/zh-cn/devops.md
Glossary `DevOps` is widely used, we can put it in title just as `CI` and `CD`.
Signed-off-by: tianzong48 <tianzong48@gmail.com>
> [zh-cn] Update DevOps

- content/en/certificate.md
- content/en/digital-certificate.md
- wordlist.txt
> [en] Certificates

- content/pt-br/cloud_computing.md
Add Brazilian Portuguese localization of **Cloud Computing** as mentioned on #269
> Add content/pt-br/cloud_computing.md

- content/pt-br/data_center.md
> Add content/pt-br/data_center.md

- content/pt-br/site_reliability_engineering.md
Add 
- content/pt-br/site_reliability_engineering.md
> Add content/pt-br/site_reliability_engineering.md

- content/pt-br/software_as_a_service.md
Add 
- content/pt-br/software_as_a_service.md
> Add content/pt-br/software_as_a_service.md

- content/pt-br/cloud_native_tech.md
Changes
* Add cloud_native_tech.md
> Add content/pt-br/cloud_native_tech.md

- content/pt-br/virtualization.md
Add
- content/pt-br/virtualization.md
> Add content/pt-br/virtualization.md

- content/pt-br/zero_trust_architecture.md
Add
- content/pt-br/zero_trust_architecture.md
> Add content/pt-br/zero_trust_architecture.md

- content/pt-br/virtual_machine.md
Add
- content/pt-br/virtual_machine.md
> Add content/pt-br/virtual_machine.md

- content/zh-cn/_index.md
- content/zh-cn/contribute/_index.md
> [zh] complete CNCF Slack link

- .github/settings.yml
@jihoon-seo and @iamNoah1 are official maintainers of the Grossary project.
With this update, @jihoon-seo and @iamNoah1 will have higher privileges. :)
> Update settings for maintainers

- content/en/load-balancer.md
If there is something to improve more, kindly point me to it.
> [en] Modify `load-balancer.md`

- content/de/cloud-native-security.md
- content/de/cloud_native_security.md
taking over https://github.com/cncf/glossary/pull/890 as contributor did not respond to anything.
> [DE] Take Over Cloud Native Security localization

- .github/settings.yml
- CODEOWNERS
Unfortunately, Adrianna stepped back from being a german reviewer :(
> remove adrianna from all files

- content/it/devsecops.md
Signed-off-by: Francesco Sbaraglia <fsbaraglia@networkadmin.it>
> [it] localizzazione termine devsecops

- content/it/distributed_system.md
Signed-off-by: Paolo [81316809+ugho16@users.noreply.github.com](mailto:81316809+ugho16@users.noreply.github.com)
> [it] localizzazione termine distributed-system

- content/it/distributed-apps.md
Signed-off-by: Paolo <81316809+ugho16@users.noreply.github.com>
> [it] localizzazione termine Distributed Apps

- content/it/monolithic-apps.md
> [it] localizzazione termine Monolithic Apps

- content/pt-br/service.md
> Add content/pt-br/service.md

- content/en/contributor-ladder/_index.md
> Added links for becoming Approver and Maintainer

- content/pt-br/infrastructure-as-code.md
Add content/pt-br/infrastructure-as-code.md
> Add content/pt-br/infrastructure-as-code.md

- LOCALIZATION.md
> Adding update discussion link to guide

- content/en/distributed-apps.md
> Link monolithic-apps

- content/en/cluster.md
> Link Kubernetes

- content/ko/microservices.md
- content/ko/monolithic-apps.md
Relevant with: https://github.com/cncf/glossary/discussions/1116#discussioncomment-3330107
> [ko] Modify architecture tag to localized terms

- content/en/blue-green-deployment.md
> Link 'load-balancer' and 'service'

- .github/settings.yml
- CODEOWNERS
This PR is to add @MrErlison as approver to the Portuguese team.
He’s a great contributor and is helping us a lot.
[Here](https://github.com/cncf/glossary/pulls?q=is%3Apr+author%3AMrErlison) you can a list of the contributions.
> [PTBR] Add MrErlison as a Portuguese approver

- content/pt-br/firewall.md
> Add content/pt-br/firewall.md

- content/en/site-reliability-engineering.md
> Add missing links

- content/bn/api-gateway.md
Signed-off-by: nazma1234 <78928674+nazma1234@users.noreply.github.com>
> [bn] Updated the status to "Completed"

- content/bn/kubernetes.md
Signed-off-by: Saber382 <78927820+Saber382@users.noreply.github.com>
> [bn] Update Kubernetes status to "Completed"

- content/en/firewall.md
> Link microservices

- content/es/.wordlist.txt
- content/es/portability.md
Closes https://github.com/cncf/glossary/issues/695
> feat: add content es/portability

- content/es/.wordlist.txt
- content/es/cloud-native-tech.md
closes https://github.com/cncf/glossary/issues/574
> [es] Localize cloud-native-tech.md

- content/en/nodes.md
> Link "virtual machine" and "cloud native"

- .github/settings.yml
- Update description of Cloud Native Glossary Repository.
- Following Pinned repositories dashboard will be updated accordingly.
> Update description of Cloud Native Glossary Repo

- layouts/_default/taxonomy.html
- layouts/partials/head.html
resolves #1291 
Signed-off-by: cjyabraham <cjyabraham@gmail.com>
> Stop incomplete terms from showing up in search results and tag listing pages

- content/en/multitenancy.md
We forgot to update the status. This term is ready :) 
> Multi tenancy completed

- .github/workflows/labeler.yml
Signed-off-by: Yunkon Kim <hermitkim1@gmail.com>
- This PR will specify a target branch on labeler workflow.
- Ref. #1322 
> Specify a target branch on labeler workflow

- content/pt-br/portability.md
Added translation for portuguese of the term Portability.
resolves #1217
> Add pt-br/docs/reference/glossary/portability.md

- content/pt-br/reliability.md
Added translation for portuguese of the term Reliability.
resolves #1218
> Add content/pt-br/reliability.md

- content/pt-br/debugging.md
Add pt-br/docs/reference/glossary/debugging.md
> Add pt-br/docs/reference/glossary/debugging.md

- .github/settings.yml
- .github/workflows/labeler.yml
- CODEOWNERS
- content/en/cloud-computing.md
This PR will update dev-ko branch with the latest changes in main branch.
> Update dev-ko with main branch

- .github/settings.yml
- .github/workflows/labeler.yml
- CODEOWNERS
This PR is to update `dev-ur` with the latest `main`, to make #1324 effective in `dev-ur` branch too.
> Update `dev-ur` with the latest `main`

- content/pt-br/scalability.md
Added translation for portuguese of the term Scalability.
resolves #1219
> Add content/pt-br/scalability.md

- content/en/database-as-a-service.md
I thought we decided that this term was beyond our scope. We should add a new category so we can remove terms while not totally not losing them. 
> DBaaS beyond Glossary scope?

- content/de/canary_deployment.md
Signed-off-by: Baris Cubukcuoglu <cubukcuoglu.baris@gmail.com>
This PR adds the german definition for Canary Deployment according to [Canary Deployment](https://glossary.cncf.io/canary-deployment/)
Resolves #512 
> [DE] Add german definition for canary deployment

- CODEOWNERS
Add David again as reviewer, some changes unintentionally removed him from the codeowners file
> Add david again as reviewer

- content/es/.wordlist.txt
- content/es/abstraction.md
This change synchronizes the changes made on the `abstraction` term to the Spanish version.
NA
> Update abstraction term

- content/es/.wordlist.txt
- content/es/agile-software-development.md
This change synchronizes the changes made on the `agile software development` term to the Spanish version.
NA
> Update agile software development term

- content/es/application-programming-interface.md
This change synchronizes the changes made on the `application programming interface` term to the Spanish version.
NA
>  Update application programming interface term 

- content/de/style-guide/_index.md
Signed-off-by: Noah Ispas (iamNoah1) <noahispas@gmail.com>
correct wording for status as only english wording gets evaluated
> correct wording for status as only english wording gets evaluated

- content/pt-br/service.md
- content/pt-br/tightly-coupled-architectures.md
Signed-off-by: Jéssica Lins <jessicaalins@gmail.com>
* The files `service.md` and `tightly-coupled-architectures.md` are currently without tags - this PR adds them
N/A
> [ptbr] Update terms that have missing tags

- content/it/service-mesh.md
> [it] Localizzazione termine Service Mesh

- content/it/loosely-coupled-architecture.md
Added Loosely coupled architecture Ialian localization
- [ x ] This PR does not contain plagiarism
- [ x ] I have signed off on all commits 
> [it] Localizzazione termine Loosely coupled architecture

- content/it/version-control.md
Added 'Version Control' Italian localization
- [ x ] This PR does not contain plagiarism
- [  x] I have signed off on all commits 
> [it] Localizzazione termine Version Control

- content/it/event-driven-architecture.md
Added Event-Driven architecture Italian localization.
- [ x ] This PR does not contain plagiarism
- [ x ] I have signed off on all commits 
> [it] Localizzazione termine Event-Driven Architecture

- content/it/tightly-coupled-architectures.md
Added tightly-coupled-architecture IT localization
NA
> [it] Localizzazione termine Tightly coupled architecture

- content/it/debugging.md
Added Debugging Italian localization
NA
> [it] Localizzazione termine Debugging

- content/it/software-as-a-service.md
Added Software as a Service (SaaS) Italian localization
> [it] localizzazione termine SaaS

- content/it/idempotence.md
Added idempotence italian localization
- [ x ] This PR does not contain plagiarism
- [ x ] I have signed off on all commits 
> [it] Localizzazione termine idempotence

- content/es/blue-green-deployment.md
This change synchronizes the changes made on the `blue-green-deployment` term to the Spanish version.
NA
> Update blue green deployment term

- content/es/canary-deployment.md
This change synchronizes the changes made on the `canary deployment` term to the Spanish version.
NA
> Update canary deployment term

- content/es/.wordlist.txt
- content/es/cloud-native-tech.md
This change synchronizes the changes made on the `cloud-native tech` term to the Spanish version.
NA
> Update cloud-native tech term

- content/es/.wordlist.txt
- content/es/cloud-native-security.md
This change synchronizes the changes made on the `cloud-native security` term to the Spanish version.
NA
> Update cloud-native security term

- content/es/cloud-native-apps.md
This change synchronizes the changes made on the `cloud-native apps` term to the Spanish version.
NA
> Update cloud native apps term

- content/es/cloud-computing.md
This change synchronizes the changes made on the `cloud computing` term to the Spanish version.
NA
> Update cloud computing term

- content/es/idempotence.md
- Converted `idempotence.md` to Spanish
- Added the new words to .wordlist.txt
resolves #1376 
Closes #1376 
> [Spanish] localize 'Idempotence'

- content/es/.wordlist.txt
- content/es/immutable-infrastructure.md
Localize the `content/en/immutable-infrastructure.md` document to Spanish
resolves #1377 
Closes #1377 
> [Spanish] localize 'Immutable Infrastructure'

- content/es/.wordlist.txt
- content/es/managed-services.md
Localization for `managed services`
Resolves #611
> [ES]Localization managed services / Passing Checks

- content/pt-br/distributed-apps.md
Added translation for portuguese of the term distributed-apps.
resolves #820
> Add /content/pt-br/distributed-apps.md

- content/es/devops.md
This change synchronizes the changes made on the `devops` term to the Spanish version.
NA
> Update devops term

- content/es/continuous-integration.md
This change synchronizes the changes made on the `continuous-integration` term to the Spanish version.
NA
> Update continuous integration term

- content/es/cluster.md
This change synchronizes the changes made on the `cluster` term to the Spanish version.
NA
> Update cluster term

- content/es/container-image.md
This change synchronizes the changes made on the `container-image` term to the Spanish version.
NA
> Update container image term

- content/es/.wordlist.txt
- content/es/event-driven-architecture.md
Signed-off-by: Irina Calvo <anairinac@gmail.com>
Created the Spanish localization for the event-driven-architecture.md document
Resolves #1373
> Create Spanish localization for event-driven-architecture.md

- content/es/reliability.md
Signed-off-by: Irina Calvo <anairinac@gmail.com>
I have created the Spanish localization for content/en/reliability.md for the Glossary
Resolves #1399
> Spanish localization for content/en/reliability.md

- content/es/continuous-delivery.md
This change synchronizes the changes made on the `continuous-delivery` term to the Spanish version.
NA
> Update continuous delivery term

- content/it/self-healing.md
Added Self Healing Italian localization
NA
> [it] Localizzazione termine Self Healing

- content/pt-br/devsecops.md
Added translation for portuguese of the term devsecops.
resolves #819
> Add /pt-br/devsecops.md

- content/pt-br/nodes.md
Added translation for portuguese of the term nodes.
resolves #1214
> Add /content/pt-br/nodes.md

- content/es/.wordlist.txt
- content/es/kubernetes.md
This change synchronizes the changes made on the `kubernetes` term to the Spanish version.
NA
> Update kubernetes term

- content/es/gitops.md
This change synchronizes the changes made on the `gitops` term to the Spanish version.
NA
> Update gitops term

- content/es/event-driven-architecture.md
This change synchronizes the changes made on the `event driven architecture` term to the Spanish version.
NA
> Update event driven architecture

- content/es/containerization.md
This change synchronizes the changes made on the `containerization` term to the Spanish version.
NA
> Update containerization term

- content/pt-br/platform-as-a-service.md
Signed-off-by: Julia Furst Morgado <52685951+juliafmorgado@users.noreply.github.com>
Create PT-BT version of platform-as-a-service.md
resolves #1216
> Create PT-BT version of platform-as-a-service.md

- content/es/.wordlist.txt
- content/es/debugging.md
Signed-off-by: Vasu Singh <vasucp1207@gmail.com>
[Spanish] localize 'Debugging
> [Spanish] localize 'Debugging

- content/it/firewall.md
Added Firewall Italian localization.
NA
> [it] Localizzazione termine Firewall

- content/en/edge-computing.md
Signed-off-by: PrathyushaModala <62796352+PrathyushaModala@users.noreply.github.com>
> Add glossary / content / en /edge-computing.md

- content/en/style-guide/_index.md
Adding a tag section and removing category. 
> Style guide update

- content/de/bare-metal-machine.md
Signed-off-by: Baris Cubukcuoglu <cubukcuoglu.baris@gmail.com>
This PR add a german definition for Bare Metal Machine (see https://glossary.cncf.io/bare-metal-machine)
Resolves #510
> Add german translation for bare metal machine

- content/es/.wordlist.txt
- content/es/nodes.md
Adding the definition of Nodes in Spanish. 
Resolves #1398 
- [ x] This PR does not contain plagiarism
- [ x] I have signed off on all commits 
> 1398 spanish localize nodes

- content/it/immutable-infrastructure.md
Added immutable infrastructure IT localization.
NA
> [it] Localizzazione termine immutable infrastructure

- content/it/multitenancy.md
Added multitenancy Italian localization.
NA
> [IT] Localizzazione termine Multitenancy

- content/it/cloud-native-tech.md
> Fixed a typo.

- content/it/observability.md
Added observability Italian localization.
> [it] Localizzazione termine Observability

- content/en/policy-as-code.md
> Policy as Code edits

- content/en/microservices-architecture.md
- content/en/microservices.md
- static/_redirects
- wordlist.txt
As discussed with maintainers, we'll change the microservices definition to microservices architecture. This is till WIP.
> Microservices > microservices architecture

- content/en/multitenancy.md
Tweak long lines to keep consistent style with other pages.
> Tweak lines in multitenancy.md

- content/pt-br/event-driven-architecture.md
Created all content of EDA Definition in PT-BR
resolves #1206
> Add glossary / pt-br / Event-Driven Architecture (#1206)

- content/es/.wordlist.txt
- content/es/contributor-ladder/_index.md
This change synchronizes the changes made on the `contributor ladder` term to the Spanish version.
NA
> Update contributor ladder index

- content/es/.wordlist.txt
- content/es/abstraction.md
- content/es/application-programming-interface.md
- content/es/auto-scaling.md
- content/es/blue-green-deployment.md
- content/es/canary-deployment.md
- content/es/client-server-architecture.md
- content/es/cloud-computing.md
- content/es/cloud-native-apps.md
- content/es/cloud-native-tech.md
- content/es/cluster.md
- content/es/continuous-delivery.md
- content/es/debugging.md
- content/es/digital-certificate.md
- content/es/event-driven-architecture.md
- content/es/event-streaming.md
- content/es/gitops.md
- content/es/idempotence.md
- content/es/immutable-infrastructure.md
- content/es/infrastructure-as-code.md
- content/es/kubernetes.md
- content/es/managed-services.md
- content/es/platform-as-a-service.md
- content/es/policy-as-code.md
- content/es/reliability.md
Update headers tag information of existing terms
NA
> Update tags in headers

- content/es/infrastructure-as-a-service.md
This change synchronizes the changes made on the `infrastructure as a service` term to the Spanish version.
NA
> Update infrastructure as a service

- content/es/.wordlist.txt
- content/es/portability.md
This change synchronizes the changes made on the `portability` term to the Spanish version.
NA
> Update portability term

- content/es/.wordlist.txt
- content/es/observability.md
This change synchronizes the changes made on the `observability` term to the Spanish version.
NA
> Update observability term

- content/es/.wordlist.txt
- content/es/contribute/_index.md
This change synchronizes the changes made on the `contribute` index to the Spanish version.
NA
> Update contribute index page

- content/fr/_TEMPLATE.md
- content/fr/container.md
Signed-off-by: Christophe Sauthier <christophe.sauthier@gmail.com>
This PR localizes `container.md` concept to French
resolves #1261 
- [ X ] This PR does not contain plagiarism
- [ X ] I have signed off on all commits 
> Traduction de container.md

- content/fr/containerization.md
Signed-off-by: Christophe Sauthier [christophe.sauthier@gmail.com](mailto:christophe.sauthier@gmail.com)
Describe your changes
This PR localizes containerization.md concept to French
Related issue number or link (ex: resolves #issue-number)
resolves https://github.com/cncf/glossary/issues/1266
Checklist before opening this PR (put x in the checkboxes)
[ X ] This PR does not contain plagiarism
don’t copy other people’s work unless you are quoting and contributing it to them.
[ X ] I have signed off on all commits
[signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: git commit -s) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco).
> [French] Traduction de containerization.md

- content/fr/monolithic-apps.md
This PR localizes monolithic-apps concept to French
Resolves #1267
> Traduction de Monolithic-apps.md

- content/es/monolithic-apps.md
Signed-off-by: Mo Figueroa <moisesdfigueroa@gmail.com>
Translates Monolithic Apps in Spanish
> [Spanish] Localize Monolitic Applications

- assets/scss/_cookie-banner.scss
- assets/scss/_styles_project.scss
- layouts/partials/head.html
Adds the standard CNCF GDPR banner. 
We want this to go live on Feb 1 with all the other CNCF sites so we have a clear break point for analytics analysis. I will leave it in a draft until then and merge on Feb 1.
Signed-off-by: cjyabraham <cjyabraham@gmail.com>
> Adds CNCF GDPR banner

- .devcontainer.json
- README.md
[GitHub Codespaces](https://docs.github.com/en/codespaces/overview) provides an easy way to deploy remote development environments. This change customize the setup process for deploying development environments.
NA
> Add codespaces support

- content/en/function-as-a-service.md
Removing proprietary product names
> FaaS: Removing proprietary product names

- content/en/contribute/_index.md
Adding a "who can contribute" to the "how to" guide to better set expectations
NA
> "who can contribute" to "how to" guide

- content/fr/virtual-machine.md
Signed-off-by: Christophe Sauthier <christophe.sauthier@gmail.com>
This PR localizes virtual-machine concept to French
Resolves https://github.com/cncf/glossary/issues/1268
- [ X ] This PR does not contain plagiarism
- [ X ] I have signed off on all commits 
> [FR] Traduction de virtual-machine.md

- content/fr/service-mesh.md
Fix #1262 
Localize content/fr/service-mesh.md to fr.
> Localize service-mesh fr

- i18n/bn.toml
- i18n/de.toml
- i18n/en.toml
- i18n/es.toml
- i18n/hi.toml
- i18n/it.toml
- i18n/ko.toml
- i18n/pt-br.toml
- i18n/zh-cn.toml
- layouts/_default/taxonomy.html
- layouts/_default/terms.html
Closes #1233 
Signed-off-by: cjyabraham <cjyabraham@gmail.com>
> i18n the word "tag" (closes #1233)

- content/es/scalability.md
Localization of `scalability.md`
resolves https://github.com/cncf/glossary/issues/1402
> [es] Localization scalability.md

- content/fr/abstraction.md
Signed-off-by: Stéphane Este-Gracias <sestegra@gmail.com>
This PR localizes abstraction to French
Resolves #1168
> [fr] Traduction pour `Abstraction`

- content/fr/cloud-native-apps.md
- content/fr/cloud-native-tech.md
Fix #1260 and #1258.
@fydrah @huats This PR needs a special focus, because I translated some important words (such as scale etc).
I think we have to review it together at our next meeting.
> Localize cloud-native apps and tech to fr

- content/en/_index.md
Expanded the description on the homepage
> Home update

- content/en/data-center.md
- wordlist.txt
Still WIP. I just made a few edits but the "problem it addresses" and "how it helps" focus on cloud computing. We'll need to adjust that. 
> Data center update

- content/es/distributed-apps.md
Localization of distributed-apps.md
It closes #600 
> ES: Localize term 'distributed apps' apps in Spanish.

- content/es/loosely-coupled-architecture.md
Add Spanish localization of ´loosely coupled architecture
This is a Spanish localization of the CNCF concept of ´loosely coupled architecture´. 
Resolves Issue #610 
> ES localization of ´Loosely coupled architecture´

- content/es/microservices-architecture.md
This change updates the references and status of the Microservices Architecture term. Changing the status to completed enables the external visibility.
#1741 
> Update Microservices architecture term

- content/es/.wordlist.txt
- content/es/containers-as-a-service.md
Add Spanish localization of containers-as-a-service.md
Issue #579 
> [ES] localization ´Containers as a Service'

- .github/settings.yml
- CODEOWNERS
Given his active [collaboration](https://github.com/cncf/glossary/pulls?q=author%3Aramrodo) in Spanish localization team, this PR recognizes the effort made by @ramrodo and promotes him to the approver role.
/cc @ramrodo @krol3
NA
> Add Rodolfo Martinez to Spanish approver team

- i18n/es.toml
This change translates the tags section located in the Spanish i18n file
NA
> [es] tags section in i18n config file

- content/es/.wordlist.txt
- content/es/firewall.md
Added `content/es/firewall.md` (translated from `content/en/firewall.md`).
* also removed draft section from the page metadata.
- resolves #1375 
> [ES] added content/es/firewall.md

- content/es/.wordlist.txt
- content/es/container-orchestration.md
- added `content/es/container-orchestration.md`.
- resolves #1762 
> [ES] added content/es/container-orchestration.md

- content/es/.wordlist.txt
- content/es/database-as-a-service.md
- added `content/es/database-as-a-service.md`.
- resolves #1763 
> [ES] added content/es/database-as-a-service.md

- content/pt-br/infrastructure-as-a-service.md
Added translation for portuguese of the term infrastructure as a service.
resolves #827
> Add /pt-br/infrastructure-as-a-service.md

- content/pt-br/monolithic-apps.md
Added translation for portuguese of the term monolithic-apps
resolves #1212
> Add /pt-br/monolithic-apps

- content/es/container.md
Localize the `content/en/container.md` document to Spanish
See more comments from a previously closed PR https://github.com/cncf/glossary/pull/1740 (Include the @krol3 suggestions)
Resolves #578
> localize 'Containers'

- .github/workflows/stale.yml
Add an action to close PR without activity in the `lang/es`
> feat: stale issues and PR with not activity

- content/it/service-proxy.md
Added Service Proxy Italian Localization
Resolves #1656 
> [it] Localizzazione termine Service Proxy

- content/es/.wordlist.txt
- content/es/horizontal-scaling.md
- added `content/es/horizontal-autoscaling.md`
- #1765 
> [ES] added content/es/horizontal-autoscaling.md

- .github/ISSUE_TEMPLATE/new-term.yml
Adding "I confirm that I meet the criteria" in one of the checkboxes.
> Issue template + confirmation to meet criteria

- .github/ISSUE_TEMPLATE/update-term.yml
> Updated 2nd issue template

- content/pt-br/microservices.md
Added translation for portuguese of the term microservices.
resolves #1211
> Add /pt-br/microservices.md

- content/pt-br/observability.md
Signed-off-by: Mr. Erlison [sisal.cordame_0a@icloud.com](mailto:sisal.cordame_0a@icloud.com)
Added translation for portuguese of the term observability.
resolves #1215
> Add /pt-br/observability

- layouts/_default/terms.html
- layouts/partials/taxonomy_terms_article.html
fixes #1911 
[Test instance](https://deploy-preview-1915--cncfglossary.netlify.app/)
> Allow tags to have spaces without breaking the filter func.

- content/ur/_index.md
Contributors added : Saim Safder, Waleed Ahmed, Asad Ali, Zubair haque
Resolved Issue #1944
> Update Urdu localization contributors name in '_index.md'

- content/es/hypervisor.md
- added `content/es/hypervisor.md`.
- #1766 
> [ES] added content/es/hypervisor.md

- content/es/contribute/_index.md
- content/es/style-guide/_index.md
- added missing sections + semantic line breaks in `content/es/style-guide/_index.md`.
- added missing section in `content/es/contribute/_index.md`.
- #1667 
> [ES] added missing sections + semantic line breaks in content/es/style-guide & content/es/contribute

- content/es/.wordlist.txt
- content/es/serverless.md
- added `content/es/serverless.md`.
- #1770 
> [ES] content/es/serverless.md

- content/es/application-programming-interface.md
- content/es/auto-scaling.md
- content/es/bare-metal-machine.md
- content/es/chaos-engineering.md
- content/es/cloud-native-security.md
- content/es/cluster.md
- content/es/container-image.md
- content/es/containers-as-a-service.md
- content/es/continuous-integration.md
- content/es/devops.md
- content/es/distributed-apps.md
- content/es/distributed-systems.md
- content/es/immutable-infrastructure.md
- content/es/infrastructure-as-code.md
- content/es/kubernetes.md
- content/es/load-balancer.md
- content/es/monolithic-apps.md
- content/es/platform-as-a-service.md
- content/es/reliability.md
- content/es/scalability.md
Update internal references to translated terms
NA
> [es] Update references

- content/fr/api-gateway.md
This PR localizes API gateway to French
Resolves #1849 
> [fr] Traduction pour `API gateway`

- i18n/ur.toml
Tags update in Urdu 
Resolves Issue #1948 
> Update tags for Urdu localization 'ur.toml'

- content/es/nodes.md
Update the latest changes on the `node` term
NA
> Sync node term

- content/es/.wordlist.txt
- content/es/security-chaos-engineering.md
- added `content/es/security-chaos-engineering.md`.
- #1768 
> [ES] content/es/security-chaos-engineering.md

- assets/scss/_footer.scss
- layouts/partials/footer.html
Makes footer consistent with all other CNCF subsites.
> Tweaks to footer layout

- content/es/software-as-a-service.md
Localized the content/en/software-as-a-service.md document into Spanish
Tracking issue: #1775 
> [es] #1775 Issue: Localized the software-as-a-service.md document

- content/en/role-based-access-control.md
- wordlist.txt
Signed-off-by: Julia Furst Morgado <52685951+juliafmorgado@users.noreply.github.com>
Added new term: Role-based access control (RBAC)
`resolves #1465`
> Add content/en/role-based access control(RBAC)

- content/es/service-mesh.md
- added `es/content/service-mesh.md`.
- #1618 
> [ES] added es/content/service-mesh.md

- content/es/bare-metal-machine.md
- content/es/virtual-machine.md
- added `es/content/virtual-machine.md`.
- fixed `máquinas virtuales` reference link in `bare-metal-machine.md`.
- #1784 
> Es virtual machine

- content/fr/distributed-systems.md
This PR adds the French translation for the `distributed-systems` concept.
Resolves #1973 
~~Commit is not signed-off yet due to not being on a laptop where I have my private GPG key. Opening the PR nonetheless to get some early feedback on it :slightly_smiling_face: Will rebase with a signed commit in a couple days.~~
> fr: add missing translation for `distributed-systems` (resolves #1973)

- content/fr/tightly-coupled-architectures.md
This PR localizes tightly-coupled-architectures concept to French
resolves #1863 
> Traduction de tightly-coupled-architectures.md

- content/fr/application-programming-interface.md
This PR localizes API to French
Resolves #1960 
> [fr] Localize API

- i18n/ko.toml
Localize UI strings related with `Tag` in ko.toml
related with https://github.com/cncf/glossary/pull/1706
> [ko] Localize UI strings in ko.toml

- content/ko/containers-as-a-service.md
Update outdated files for Korean.
- container-as-a-service.md (rename and add draft:true)
[ko] A report to track update #1924
- container-as-a-service.md
> [ko] Update and rename container-as-a-service.md

- content/it/service-discovery.md
Added Service discovery italian localization
Closes #1655 
> [it] Localizzazione termine Service Discovery

- content/it/mutual-transport-layer-security.md
Added mTLS Italian localization
Closes #1603 
> [it] Localizzazione termine mTLS

- content/it/kubernetes.md
Added Kubernetes Italian localization
Resolves #1652 
> [it] Localizzazione termine Kubernetes

- content/it/bare-metal-machine.md
Added Bare Metal Machine Italian localization
Resolves #1598 
> [it] Localizzazione termine Bare Metal Machine

- content/it/application-programming-interface.md
Added API italian localization
Resolves #1601 
> [it] Localizzazione Application Programming Interface (API)

- content/it/blue-green-deployment.md
Added Blue-Green deployment Italian localization
Resolves #1646 
> [it] Localizzazione Blue Green Deployment

- content/es/.wordlist.txt
- content/es/function-as-a-service.md
- added `es/content/function-as-a-service`.
- added `FaaS` to `wordlist.txt`.
- #602
- #602 
> [ES] es-function-as-a-service

- .github/settings.yml
- .github/workflows/check-outdated-content.yaml
- .github/workflows/post-outdated-content-report.yaml
- CODEOWNERS
Merge `main` branch setting related to `dev-tw` into branch
> Merge latest CODEOWNERS into dev-tw

- config.toml
- Add space between each language name in their own language (e.g., `한국어`) and its corresponding English name (e.g., `(Korean)`)
- AFAIK maintainers agreed to do so someday ago..?
- `中文(Chinese)` → `简体中文 (Simplified Chinese)`
- To adopt 'Traditional Chinese' alongside in near future
None
> Update lang names in `config.toml`

- content/es/service-discovery.md
- added `content/es/service-discovery`.
- resolves #1788 
> [ES] added content/es/service-discovery

- content/es/stateful-apps.md
- added `content/es/stateful-apps.md`.
- resolves #1776 
> [ES] added content/es/stateful-apps.md

- content/es/edge-computing.md
- added `compute/es/edge-computing.md`.
- resolves #1764 
> [ES] added compute/es/edge-computing.md

- content/ko/_index.md
Update outdated Korean _index.md (a task in #1924)
#1924
> [ko] Update outdated Korean _index.md

- content/fr/self-healing.md
Localize `Self Healing` in French
Resolves #1996 
> [FR] Localize `Self Healing`

- content/es/_TEMPLATE.md
- added `es/_TEMPLATE.md`.
- resolves #1778 
> [ES] content/es/_TEMPLATE.md

- content/es/abstraction.md
- content/es/blue-green-deployment.md
- content/es/event-driven-architecture.md
- content/es/function-as-a-service.md
- content/es/microservices-architecture.md
- content/es/service-mesh.md
- content/es/service.md
- Added service.md file with
- Change Linked Concept in Followiing files: 
- content/es/abstraction.md
- content/es/blue-green-deployment.md
- content/es/event-driven-architecture.md
- content/es/function-as-a-service.md
- content/es/microservices-architecture.md
- content/es/service-mesh.md
> [ES] Service.md

- content/es/.wordlist.txt
- content/es/search.md
This commit updates the text  _Site Results_ to _Resultados de la búsqueda_ to provide a version in Spanish.
> [ES] /content/es/search.md

- content/es/.wordlist.txt
- content/es/mutual-transport-layer-security.md
- added `es/mutual-transport-layer-security.md`.
- resolves #1397 
> [ES] content/es/mutual-transport-layer-security.md

- content/es/kubernetes.md
- content/es/self-healing.md
- Add Spanish translated version of Self-Healing
- Add the link in the Kubernetes file where the concept is referenced
> Es self healing

- content/es/version-control.md
- Added the translated version of version control
> [ES] Version Control

- content/es/zero-trust-architecture.md
Added the translated version of the Zero trist architecture.
resolves #1785
> Added the translated version of the Zero trust architecture.

- content/en/style-guide/_index.md
Copy edit pass on Style Guide page.
n/a
> Copy edit pass on style-guide page

- content/fr/service.md
This PR localizes Service to French
Resolves https://github.com/cncf/glossary/issues/2092
> [fr] Localize Service

- content/fr/observability.md
This PR localizes Observability to French
Resolves #1961 
> [fr] Localize Observability

- .github/settings.yml
Update branch setting to.
1. Add `dev-tr` and Turkish localization approvers (external_collaborators with write) https://github.com/cncf/glossary/issues/2123
Add: @aliok
Add: @halil-bugol
Add: @developer-guy
Add: @eminalemdar
2. Replace Bengali localization approvers. https://github.com/cncf/glossary/pull/2100
Remove: @Mouly22 @ikramulkayes
Add: @Arindam200 @sajibAdhi
- https://github.com/cncf/people/pull/248
- https://github.com/cncf/glossary/pull/2134
- [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add …
> Update settings.yml for Tr and Bn approvers

- content/es/.wordlist.txt
- content/es/shift-left.md
Added `es/shift-left.md`.
This PR includes changes/work from this other stale PR: https://github.com/cncf/glossary/pull/1871
resolves https://github.com/cncf/glossary/issues/1773
> [ES] added content/es/shift-left.md

- content/es/.wordlist.txt
- content/es/stateless-apps.md
Localize "Stateless app" into Spanish
Resolves #1777 
> [ES] Localize stateless app

- content/fr/loosely-coupled-architectures.md
This PR localizes Loosely Coupled Architecture concept to French
resolves #2029 
> [FR] Traduction de Loosely Coupled Architecture into French

- content/fr/reliability.md
This PR localizes Reliabiliry to French
Resolves #1997 
> [fr] Localize Reliability

- .github/settings.yml
- .github/workflows/es-spellcheck.yml
- .github/workflows/spellcheck.yml
- .gitignore
- CODEOWNERS
- content/en/_index.md
- content/en/style-guide/_index.md
- spin-new-glossary.md
Update some files from main branch.
> Follow the latest commit in main branch

- content/fr/distributed-apps.md
This PR localizes Distributed Apps to French
Resolves https://github.com/cncf/glossary/issues/2149
> [FR] localize Distributed Apps

- content/fr/virtualization.md
This PR localizes Virtualization to French
Resolves https://github.com/cncf/glossary/issues/2144 
I didn't translate the last sentence, as it does't seem to make sense. I opened an issue about that: https://github.com/cncf/glossary/issues/2143
> [fr] Localize Virtualization

- .github/settings.yml
- CODEOWNERS
Cherry-pick commit from. `main` branch
N/A
> [fr] Add sestegra as an fr approver in dev-fr branch

- content/fr/bare-metal-machine.md
This PR localizes bare metal machine to French
Resolves https://github.com/cncf/glossary/issues/2125 
> [fr] Localize bare metal machine

- content/fr/nodes.md
This PR localizes Nodes to French
Solves https://github.com/cncf/glossary/issues/2146
> [FR] localize Nodes

- content/fr/abstraction.md
- content/fr/agile-software-development.md
- content/fr/api-gateway.md
- content/fr/application-programming-interface.md
- content/fr/cloud-native-apps.md
- content/fr/cloud-native-tech.md
- content/fr/distributed-systems.md
- content/fr/infrastructure-as-code.md
- content/fr/monolithic-apps.md
- content/fr/tightly-coupled-architectures.md
- content/fr/virtual-machine.md
Align frontmatter with `main` branch
N/A
> [fr] update frontmatters

- content/en/pod.md
created pod.md
resolves #1989 
> [EN] add Pod

- content/es/.wordlist.txt
- content/es/service-proxy.md
- added `content/es/service-proxy.md`
- resolves #1772 
> [ES] added content/es/service-proxy

- config.toml
Fix merge conflicts for future merges from main into dev-fr
N/A
> [fr] Fix merge conflicts on config.toml

- content/es/tightly-coupled-architectures.md
Localize "Tightly Coupled Architectures" to Spanish
Resolves #1779
> [ES] Localize Tightly Coupled Architectures

- content/fr/virtualization.md
[Fr] update Virtualization following issue https://github.com/cncf/glossary/issues/2143:
Remove last sentence
issue https://github.com/cncf/glossary/issues/2143
> [FR] update Virtualization following issue 2143

- content/fr/containerization.md
Following this PR, doing the same for the not merged yet FR branch : https://github.com/cncf/glossary/pull/2198
Only one occurence found
https://github.com/cncf/glossary/pull/2198
> [FR] Remove links to 'Deprecated' / 'Feedback Appreciated' terms

- content/de/containers.md
added german localization for containers
- [x ] This PR does not contain plagiarism
> 1409 german localize containers

- content/fr/immutable-infrastructure.md
Localize immutable infrastructure in French
resolves #2221
> [FR] Localize immutable infrastructure

- content/fr/auto-scaling.md
Localize `Autoscaling` in French
Resolves #2016 
> [fr] Localize autoscaling

- content/fr/search.md
Localize `search` in French
#2204 
> [fr] Localize search

- content/fr/idempotence.md
Localize idempotence in French
resolves #2203 
> [fr] Localize idempotence

- content/fr/container.md
Reput the translation for container in French
resolves #2200 
> Reput the french translation for container

- content/fr/kubernetes.md
This PR localize Kubernetes into french.
Resolves #2038 
> Initialize traduction of Kubernetes into french

- content/de/cluster.md
A new approach to localize the term Cluster 
#1407
deprecates #1967
Thanks @bjoernschotte for the contribution, this is a new approach. I opened a new issue in order to update the English term accordingly. #2210
> [DE] localize Cluster

- content/fr/cluster.md
Localize cluster into French 
Fix #2041 
> [FR] Initialize cluster into French

- config.toml
Please see #2223
Resolves #2223
> Update `config.toml` to resolve warnings

- content/fr/devops.md
Add `DevOps` french translation.
resolves #1264 
> [fr] Localize term DevOps

- content/tr/_index.md
- Added `content/tr` directory for Turkish translations
- Added Turkish translation for `_index.md`
- [`_index.md`](https://docs.google.com/document/d/1X0Rph6-CZYSE27qRzpi9_L2uZIa9JespFZ0BG5SV9W4/edit?usp=sharing)
> [tr] Add Turkish translation for _index.md

- content/it/containers-as-a-service.md
- content/it/debugging.md
- content/it/firewall.md
- content/it/managed-services.md
- content/it/platform-as-a-service.md
- content/it/software-as-a-service.md
- content/it/version-control.md
- content/it/vertical-scaling.md
aggiunto termine vertical scaling e deprecati termini , issue #1657 #1660
> aggiunto termine vertical scaling e deprecati termini , issue #1657 #1660

- CODEOWNERS
This PR is to make GitHub request reviews to localization approvers of each language when a PR that touches `i18n/xx.toml` gets opened.
resolves #2199
Note: if we are to adopt this, then we need to manage & update `i18n/data/xx/CODEOWNERS` files when the root `CODEOWNERS` file gets changed, to make them synced well.
When merging this PR, please merge using 'Squash and …
> [i18n] Add `xx.toml` entries to CODEOWNERS

- .github/settings.yml
- config.toml
Fix the duplicated `ur` configuration block in `config.toml` and add updates from #2238 
N/A
> [FR] Fix previous merge

- i18n/fr.toml
Update localization for `i18n/fr.toml`
Resolves #2253
> [FR] Update localization for i18n/fr.toml

- content/fr/cloud-computing.md
localize `Cloud Computing` in french
Solves https://github.com/cncf/glossary/issues/1263
> [FR] localize `Cloud Computing`

- content/tr/cloud-computing.md
- Added Turkish translation for `cloud-computing.md`
Google Docs for reference:
- [`cloud-computing.md`](https://docs.google.com/document/d/10yJ1yqbQhyVvrAhMILB5JrVbmBMjoWYBGmjSrXjkSqA/edit?usp=sharing)
> Add Turkish localization for cloud-computing.md

- content/pt-br/continuous-deployment.md
Added the complete definition of `Continuous Deployment` in **PT-BR**
Resolves issue https://github.com/cncf/glossary/issues/816
> add pt-br/continuous-deployment

- content/tr/cloud-native-tech.md
Localize "Cloud Native Tech" page into Turkish
> [tr] Add Turkish localization for cloud native tech

- content/it/serverless.md
Added Serverless Italian localization
resolves #1654 
> [it] Localizzazione Serverless

- content/it/zero-trust-architecture.md
Added Zero Trust Architecture Italian localization
Resolves #1659 
> [it] Localizzazione termine Zero Trust Architecture

- content/zh-tw/kubernetes.md
Origin content from https://glossary.cncf.io/kubernetes/
resolves #2297
> [tw] Localize Kubernetes for Traditional Chinese

- content/es/.wordlist.txt
- content/es/service-mesh.md
This change fixes a typo (removal of the`]` character) and includes the English term just for reference as we have previously done with other concepts.
N/A
> [ES] updated  content/es/service-mesh.md

- content/it/security-chaos-engineering.md
Signed-off-by: annalisag-spark <83414097+annalisag-spark@users.noreply.github.com>
Localization of Security Chaos Engineering
- [x ] I have signed off on all commits 
> [it] Localization security-chaos-engineering.md

- content/it/cloud-computing.md
Added Cloud computing italian localization
Resolves #1647 
> [it] Localizzazione termine Cloud computing

- content/it/virtualization.md
Added Virtualization italian localization
resolves #1658 
> [it] Localizzazione termine Virtualization

- content/pt-br/distributed-systems.md
Added `Distribute Systems`
Resolve issue https://github.com/cncf/glossary/issues/821
> add distributed-system

- content/zh-tw/_index.md
1. Update [_index.md](https://github.com/cncf/glossary/blob/main/content/en/_index.md) for Traditional Chinese
2. **Add acknowledgement for initial localization contributors list**, Ref: [Slack](https://cloud-native.slack.com/archives/C055KERTNCX/p1692178242401859?thread_ts=1692000829.086109&cid=C055KERTNCX).
3. Adjust the way the article is described to make the sentences flow more smoothly.
4. Origin content is updated https://github.com/cncf/glossary/pull/2343
5. Adjust the translation of "cloud native" in Traditional Chinese to "雲端原生"
Updated information:
- https://github.com/cncf/glossary/pull/2141
- https://github.com/cncf/glossary/pull/2268
- https://github.com/cncf/glossary/pull/2343
resolves #2357
- don’t copy other people’s work unless you are quoting and contributing it to …
> [tw] Update _index.md for Traditional Chinese 

- content/es/.wordlist.txt
- content/es/role-based-access-control.md
Localize the document content/en/role-based-access-control.md to spanish
resolve #2186
> [es] Localize role-based-access-control (RBAC) #2186

- content/fr/_index.md
Update `_index.md` before merging in `main` branch.
Resolves #2368 
> [FR] Update _index.md

- content/zh-tw/contribute/_index.md
1. Update `contribute/_index.md` for Traditional Chinese
2. https://glossary.cncf.io/contribute/
3. Origin content is updated https://github.com/cncf/glossary/pull/2343
4. Improve formatting and add links
Update Information:
- https://github.com/cncf/glossary/pull/2343
- https://github.com/cncf/glossary/pull/2268
resolves #2356
> [tw] Update `contribute/_index.md` for Traditional Chinese

- content/fr/cloud-native-security.md
Localize Cloud Native Security into French. Close #2289
> Localize Cloud Native Security in french

- content/fr/IaaS.md
IaaS french translation
Issue resolved #2276 
> localization of IaaS FR

- content/fr/continuous-integration.md
Localize `Continuous Integration` to french
solves https://github.com/cncf/glossary/issues/2292
> [FR] Localize `Continuous Integration`

- content/it/function-as-a-service.md
Signed-off-by: annalisag-spark <83414097+annalisag-spark@users.noreply.github.com>
Localized FaaS into Italian.
Resolves issue #1600 
> [it] Localization function-as-a-service.md

- content/ko/_index.md
This PR reflects changes in the main branch.
#2387
> [ko] Update _index.md

- content/it/container-orchestration.md
localize it Container-Orchestration
#1648 
> localize-Container-Orchestration-#1648

- content/it/data-center.md
I saw an abandoned issue about the translation of this term, so I made a new translation of the term
#2011 
> localize-datacenter-#2011

- content/fr/devsecops.md
[FR] localize `DevSecOps`
Solves https://github.com/cncf/glossary/issues/2293
> [FR] localize `DevSecOps`

- content/it/contributor-ladder/_index.md
Add localization of `/contributor-ladder/index.md`
#2526 
> [it] Localization Contributor Ladder

- content/fr/continuous-delivery.md
[FR] Localize `Continuous Delivery` to French
Solves https://github.com/cncf/glossary/issues/2290
> [FR] Localize `Continuous Delivery` to French

- i18n/hi.toml
Translate Remaining English String into hindi language
#2182 
> Localize hi.toml

- content/zh-tw/_TEMPLATE.md
1. [tw] Localize `_TEMPLATE.md`  for Traditional Chinese
2. en : https://github.com/cncf/glossary/blob/main/content/en/_TEMPLATE.md
3. Other languages, such as `ko` : https://github.com/cncf/glossary/blob/main/content/ko/_TEMPLATE.md
This document has been translated according to other language translation standards
resolves #2588
> [tw] Localize `_TEMPLATE.md`  for Traditional Chinese

- content/en/microservices-architecture.md
> [en] Fix typo

- content/tr/agile-software-development.md
Completed translation of agile-software-development.md.
> [tr] Agile software development translation

- content/fr/policy-as-code.md
Localize `Policy as Code`
Resolved #2563 
> [FR] Localize `Policy as Code`

- content/tr/infrastructure-as-code.md
- Added Turkish localization for infrastructure-as-code.md
- [`infrastructure-as-code.md`](https://docs.google.com/document/d/13LmCPLw-FTBkBaFaZlAeYYpHABJd4gRxbxrArWjINhE)
> [tr] Add Turkish localization for infrastructure-as-code.md

- content/tr/container-orchestration.md
- Add a link in container orchestration page
> [tr] Add a link in container orchestration page

- content/en/ingress.md
Updated the ingress.md file as required.
- changed status to completed
- removed empty tags
- closes #2663
- signed the commits ✔️
> [EN] update Ingress

- content/tr/cluster.md
Add Turkish l10n for Cluster
Google Doc: https://docs.google.com/document/d/1Bkwod1VmeBbyxM65vk-hKG-JU7rLH1BgUXQ_GdIpSrU
Preview: https://deploy-preview-2698--cncfglossary.netlify.app/tr/cluster/
> Add Turkish localization for Cluster

- content/tr/observability.md
Add Turkish l10n for Observability
Google Doc: https://docs.google.com/document/d/18zCoBepHn9t3w4pI8OGcMrHw-Ff-PTmNTkBf4GgrUhQ/edit
Preview: https://deploy-preview-2698--cncfglossary.netlify.app/tr/observability/
> [tr] Add Turkish l10n for Observability

- config.toml
This PR includes manually merged config.toml file (from upstream/main and configuration in dev-ja)
- on the latest dev-ja branch, `git checkout upstream/main -- config.toml`
- manually added the existing configuration part in ja into the config.toml from main branch
Hopefully, https://github.com/cncf/glossary/pull/2700 can be fixed by this PR.
> Manually merge changes for ja in config.toml

- i18n/ar.toml
This pull request will add localization strings to `ar.toml` to translate the feedback section on the glossary entry pages.
No issue assigned.
> Localize feedback section to Arabic

- content/tr/reliability.md
Add Turkish localization for Reliability
Google Doc https://docs.google.com/document/d/1Puni4Grxlv_sU-LiaYesylt7-T1lHW4k9123W6s3he4/edit#heading=h.mo94ylk0tzfj
> Add Turkish localization for reliability.md

- content/tr/continuous-delivery.md
Add Turkish localization for Continuous Delivery
Google Doc https://docs.google.com/document/d/1tpRtXeJO3D2yNDLKFYCjydWfMgQ1aa8P2wgN0hNhO-0/edit#heading=h.mo94ylk0tzfj
> Add Turkish localization for continuous-delivery.md

- content/tr/abstraction.md
- content/tr/agile-software-development.md
- content/tr/cloud-computing.md
- content/tr/cloud-native-tech.md
- content/tr/cluster.md
- content/tr/container.md
- content/tr/containerization.md
- content/tr/infrastructure-as-code.md
- content/tr/observability.md
- content/tr/site-reliability-engineering.md
Translate the tags into Turkish
Related issue https://github.com/cncf/glossary/issues/2294
> Translate tags to TR

- content/tr/application-programming-interface.md
Turkish localization for Application Programming Interface is added
Google Doc: https://docs.google.com/document/d/1Gsk3_a0ONBpg1YUSbVfnTnp2oIvMW7a-PVnetcbNcmM/edit
Preview: https://glossary.cncf.io/application-programming-interface/
> Add Turkish localization for Application Programming Interface

- content/fr/data-center.md
Localize `Datacenter`  in French
solves https://github.com/cncf/glossary/issues/2642
> [FR] localize `Datacenter` 

- content/fr/mutual-transport-layer-security.md
Localize `Mutual Transport Layer Security (mTLS)` in French
solves https://github.com/cncf/glossary/issues/2647
> [FR] Localize `Mutual Transport Layer Security (mTLS)`

- content/en/bare-metal-machine.md
Proposed minor changes in the docs and changed it.
> Changes need to be applied for the Glossary for Bare Metal Server

- content/fr/pod.md
Localize `pod` in French
Resolves  https://github.com/cncf/glossary/issues/2756
> [FR] Localize `pod`

- i18n/ar.toml
This pull request will update the Arabic localization strings
for all tag and tag-search related terms.
No issue assigned.
> [ar] Update Arabic localization of tag strings

- content/en/continuous-delivery.md
Following issue https://github.com/cncf/glossary/issues/2433
The last sentence of the [Continuous Delivery ](https://glossary.cncf.io/continuous-delivery/)term says:
"Typically, trunk-based development is used in CD strategies as opposed to feature branching or pull requests"
It is highly unlikely that the reader knows what "trunk-based development" is, as he is reading the glossary to learn more about Continuous Delivery.
I completly removed this sentence, as it's not necessary to understand what Continuous Delivery means, and it is confusing
resolves https://github.com/cncf/glossary/issues/2433
- [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commit …
> [EN] update `Continuous Delivery`

- content/fr/data-center.md
Fix links in `data-center`
N/A
> [FR] Fix links in `data-center.md`

- content/fr/data-center.md
- content/fr/mutual-transport-layer-security.md
Fix some links that are incorret.
N/A
> [FR] Merge dev-fr branch into main branch for fixing links

- content/fr/runtime.md
Localize `Runtime` in French
Resolves #2729 
> [FR] Localize `Runtime`

- content/ja/_index.md
Add initial localization contributors list in _index.md
> Add initial localization contributors list

- content/en/ebpf.md
Adding tags in ebpf.md
resolves #2862
- [x ] This PR does not contain plagiarism
- [x ] I have signed off on all commits 
> [en] Adding tags in  ebpf.md

- content/ja/_index.md
**Following the upstream**
- update contributors/maintainers
- add the paragraph regarding the Emeritus Maintainers
**minor fixes**
- remove comma
- change the period to the kutenn(`。`)
- add the newline at the end of the file.
- GitHub comment: https://github.com/cncf/glossary/pull/2809#issuecomment-1895363180
- Slack: https://cloud-native.slack.com/archives/C02N2RGFXDF/p1706511157815389?thread_ts=1706414657.825829&cid=C02N2RGFXDF
- [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your …
> [ja] Following the upstream for `content/ja/_index.md` and minor fixes

- content/bn/ebpf.md
Adding tags in ebpf.md
- [ x] This PR does not contain plagiarism
- [x ] I have signed off on all commits 
> [bn] adding tags in ebpf.md

- i18n/it.toml
IT localization of the page search by tags
#1760 
> “it-localization-category-#1760”

- content/it/ingress.md
Ingress italian localization, new term
#2711 
> “it-localization-ingress-#2711”

- content/tr/stateful-apps.md
stateful-apps.md localization to Turkish
> [tr] Add Turkish localization for stateful-apps.md

- content/tr/event-driven-architecture.md
event-driven-architecture.md localization to Turkish
> [tr] Add Turkish localization for event-driven-architecture.md

- content/tr/distributed-systems.md
distributed-systems.md localization to Turkish
> [tr] Add Turkish localization for distributed-systems.md

- content/tr/distributed-apps.md
distributed-apps.md localization to Turkish
> [tr] Add Turkish localization for distributed-apps.md

- content/fr/ebpf.md
Localize `eBPF` in French
Resolves https://github.com/cncf/glossary/issues/2731
> [FR] Localize `eBPF`

- content/fr/serverless.md
Localize `serverless` in French
Resolves https://github.com/cncf/glossary/issues/2761
> [FR] localize `serverless`

- content/tr/transport-layer-security.md
Google Doc: https://docs.google.com/document/d/12Tm9U-OAuIKc1sWmCSrAPX2V85vxZ_vWh2gA47NjxdQ/edit
Preview: https://deploy-preview-2941--cncfglossary.netlify.app/tr/transport-layer-security/
> Add Turkish Localization to Transport Layer Security Page 

- content/tr/cloud-native-security.md
Google Doc: https://docs.google.com/document/d/1ftMwZh-mn7d9FC9nWbaDYoT5gNhgG9TstAv5yb66nu8/edit
Preview: https://deploy-preview-2943--cncfglossary.netlify.app/tr/cloud-native-security/
> [tr] Add Turkish Localization to Cloud Native Security Page 

- content/tr/cloud-native-apps.md
Describe your changes
Google Doc: https://docs.google.com/document/d/1whGOMsVfFoieXnZGotlz9zjiC_fG2lcz/edit
Preview: https://deploy-preview-2945--cncfglossary.netlify.app/tr/cloud-native-apps/
Related issue number or link (ex: resolves #issue-number)
Checklist before opening this PR (put x in the checkboxes)
This PR does not contain plagiarism
don’t copy other people’s work unless you are quoting and contributing it to them.
I have signed off on all commits
[signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: git commit -s) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your gitconfig by running git config --global alias.ci "commit -s".
> Add Turkish localization for cloud-native-apps

- content/tr/virtualization.md
- Added Turkish localization for virtualization.md
- [`virtualization.md`](https://docs.google.com/document/d/1MAEM4Xn0jIzc6Quf9dS9G9_Foas7G3g4aKyJTCH1tog)
> [tr] Add Turkish localization for virtualization.md

- content/tr/mutual-transport-layer-security.md
Google Doc: https://docs.google.com/document/d/1WMQvIRxSj8z2ACs2cmzgYeiLZKHiU8LC0cA7xuHNpl0/edit
Preview: https://deploy-preview-2698--cncfglossary.netlify.app/mutual-transport-layer-security/
> [tr] Add Turkish Localization to mutual Transport Layer Security Page

- content/fr/architecture-server-client.md
- content/fr/client-server-architecture.md
Added architecture server client translation
resolves  #2568
> [FR] Added architecture server client translation

- .github/workflows/post-outdated-content-report.yaml
- content/en/ebpf.md
- content/en/edge-computing.md
update term edge-computing
resolves #2886
> [EN] update term edge-computing

- CODEOWNERS
Suggest that @pichuang 's own permissions be transferred to @tico88612 , who can contribute more to the glossary project
> Replace @pichuang with @tico88612 as zh-tw branch approver

- content/fr/edge-computing.md
Update the the terms edge-computing FR version after  PullRequest https://github.com/cncf/glossary/pull/2905 Merge on VO (EN).
resolves #2978 
> [FR] Update Term according VO Change

- content/fr/shift-left.md
Localize shift left
resolves #2955
> [FR] Localize Shift Left

- content/tr/event-streaming.md
docx: https://docs.google.com/document/d/1SK54gRDmWZe4w9down5U-_M8cQE1-vbh/edit
netlify: https://deploy-preview-2972--cncfglossary.netlify.app
> [tr] Add Turkish localization for event-streaming.md

- content/pt-br/edge-computing.md
Localize https://glossary.cncf.io/edge-computing/
https://github.com/cncf/glossary/issues/2381
> add pt-br/edge-computing

- content/de/_TEMPLATE.md
- content/de/agile-software-development.md
- content/de/api-gateway.md
- content/de/application-programming-interface.md
- content/de/autoscaling.md
- content/de/bare-metal-machine.md
- content/de/blue-green-deployment.md
- content/de/canary-deployment.md
- content/de/client-server-architecture.md
- content/de/cloud-computing.md
- content/de/cloud-native-apps.md
- content/de/cloud-native-security.md
- content/de/cloud-native-tech.md
- content/de/cluster.md
- content/de/containers.md
Remove What it is header in all existing german content. 
#2242 
> remove what it is header

- content/fr/event-streaming.md
Localize event streaming
resolves #2947 
> [FR] Localize Event Streaming

- content/tr/scalability.md
- Added Turkish localization for scalability.md
- [`scalability.md`](https://docs.google.com/document/d/1rbfXcgQWsOfzhAi1_kJXL-WbkhCLeDEACOUYe9ElKE8)
> [tr] Add Turkish localization for scalability.md

- content/tr/_index.md
> [tr] new contributors

- content/ru/_index.md
Applying small changes to `_index.md` before we can merge `dev-ru` to `main` (as requested by @seokho-son).
#3031
> [ru] Update _index.md before merging dev-ru

- content/de/continuous-integration.md
- [ X] This PR does not contain plagiarism
- [X ] I have signed off on all commits 
> 2532 german localize continuous integration

- content/fr/service-discovery.md
Localize Service Discovery
resolves #2985
> [FR] Localize Service Discovery

- content/fr/function-as-a-service.md
[FR] localize `Function as a Service`
Fixes https://github.com/cncf/glossary/issues/2782
> [FR] localize `Function as a Service`

- content/tr/devops.md
Add Turkish I10n for DevOps
Google Doc: https://docs.google.com/document/d/1kX_JAtZo9FnEeJtTV-zZQt4Wu0PxS0skxCBp1v_nF4k/edit#heading=h.mo94ylk0tzfj
Preview: https://deploy-preview-2698--cncfglossary.netlify.app/tr/devops/
> Add Turkish localization for DevOps

- content/fr/service-proxy.md
Localize `service proxy`
#3028 
> [FR] Localize `Service Proxy`

- content/tr/monolithic-apps.md
monolithic-apps.md localization to Turkish
> [tr] Add Turkish localization for monolithic-apps.md

- content/tr/loosely-coupled-architecture.md
loosely-coupled-architecture.md localization to Turkish
> [tr] Add Turkish localization for loosely-coupled-architecture.md

- content/pt-br/chaos-engineering.md
Localize https://glossary.cncf.io/chaos-engineering/
resolves issue https://github.com/cncf/glossary/issues/814
> add pt-br/chaos-engineering

- content/fr/site-reliability-engineering.md
localize `Site Reliability Engineering` in French
solves https://github.com/cncf/glossary/issues/2974
> [FR] localize `Site Reliability Engineering`

- content/fr/chaos-engineering.md
localize `Chaos Engineering` in French
solves https://github.com/cncf/glossary/issues/3000
> [FR] localize `Chaos Engineering`

- content/fr/tightly-coupled-architecture.md
Rename tightly-coupled-architectures.md to tightly-coupled-architecture.md
N/A
> [FR] Renamed to `tightly-coupled-architecture.md`

- content/pt-br/chaos-engineering.md
- content/pt-br/edge-computing.md
Merge dev-pt in the main branch
N/A
> [PTBR] Merge dev-pt in the main branch

- content/tr/portability.md
docx: https://docs.google.com/document/d/1HMavy9ujC-aPJ7YssG5VpmtoMOVxJJ32k-ni7VjEvZ4/edit
netlify: https://deploy-preview-3063--cncfglossary.netlify.app/
> [tr] Add Turkish localization for 'portability'

- content/fr/stateful-apps.md
Localize `Stateful Apps` in French
#3136 
> [FR] Localize `Stateful Apps`

- content/it/policy-as-code.md
Policy as code update on italian branch, removed Cos'è and draft
#3104 
> it-update policy as code term #3104

- content/pt-br/container-orchestration.md
Localize https://glossary.cncf.io/container-orchestration/.
resolves #2379 
> dev-pt-2379 container orchestration

- content/es/.wordlist.txt
- content/es/pod.md
This PR will add a new file `content/es/pod.md` localizing the glossary entry "pod" into Spanish.
resolves #2951 
> [es] localize pod into spanish

- .github/settings.yml
- CODEOWNERS
@fydrah decided to step down
@seb-835 has been promoted as approver
The entire dev-fr team:
- shouts out @fydrah for his support, reviews and contributions on dev-fr.
- congratulates @seb-835 on his promotion as approver on dev-fr.
N/A
> Update dev-fr contributors

- content/es/.wordlist.txt
- content/es/serverless.md
Update "Serverless" term in Spanish which is outdated right now.
References of Spanish concepts used:
- [abstrae](https://www.rae.es/dpd/abstraer)
- [computación sin servidor](https://azure.microsoft.com/es-mx/resources/cloud-computing-dictionary/what-is-serverless-computing/)
resolves https://github.com/cncf/glossary/issues/3228 
> [es] Update "Serverless" term in Spanish

- content/fr/canary-deployment.md
- content/fr/security-chaos-engineering.md
> [FR] Fix typo in titles

- content/pt-br/pod.md
> add pt-br/pod (#3181)

- content/fr/multitenancy.md
Localize multitenancy in French
Close #2996.
For reviewers : J'ai longuement hésité entre mutualisation et colocation. Je dois avouer qu'après m'être relu je trouve que colocation est plus appropriée,  WDYT ?
> [FR] localize multitenancy

- content/pt-br/gitops.md
This PR adds gitops to pt-br.
resolves #3180 
> feat(pt-br): add gitops

- content/fr/chaos-engineering.md
- content/fr/cloud-native-apps.md
- content/fr/devops.md
- content/fr/function-as-a-service.md
- content/fr/loosely-coupled-architecture.md
- content/fr/microservices-architecture.md
- content/fr/stateful-apps.md
Fix links before merging to main
needed before merging this PR: https://github.com/cncf/glossary/pull/3270
> [FR] fix links

- content/fr/vertical-scaling.md
[FR] update `vertical scaling` after changes in English.
The second link to horizontal-scaling was removed, following guidelines.
see https://github.com/cncf/glossary/pull/2590 for details about this change
> [FR] update `vertical scaling`

- content/fr/observability.md
[FR] update `observability` following changes in English version
Only the link to the Cloud Native Landscape was changed
N/A
> [FR] update `observability`

- content/fr/continuous-delivery.md
[FR] update `continuous delivery` after changes in English version
N/A
> [FR] update `continuous delivery`

- content/fr/cloud-native-tech.md
update `cloud-native-tech` after changes in English version
N/A
> [FR] update `cloud-native-tech`

- content/fr/idempotence.md
[FR] update `idempotence` following changes in English
N/A
> [FR] update `idempotence`

- content/bn/search.md
Update search.md
before 
after
> [bn] Update search.md

- layouts/partials/head.html
Related to an [existing PR](https://github.com/cncf/glossary/pull/3314) but a different approach. This adds a Hello Bar / announcement bar to the site. Creating this PR to preview the [implementation](https://github.com/cncf/cncf.io/pull/886) and compatibility with Docsy.
> Adding Hello Bar script

- content/ru/digital-certificate.md
- content/ru/distributed-systems.md
Translate title - distributed-systems.md
Translated titles for two terms, `Digital certificate` and `Distributed System`
> Translate titles: Digital certificate and Distributed System

- content/de/continuous-deployment.md
- [X ] This PR does not contain plagiarism
- [X ] I have signed off on all commits 
> 2530 german localize continuous deployment

- content/en/style-guide/_index.md
added the sign language video style guide
Added an anchor link under Audience and added the video style guide after getting started with a google doc
related to issue [#3040](https://github.com/cncf/glossary/issues/3044#issue-2239321408)
> Add Sign Language Video Style Guide to index.md

- content/fr/horizontal-scaling.md
Update `Horizontal Scaling` in French following this PR: https://github.com/cncf/glossary/pull/3241
Update `Horizontal Scaling` in French following this PR: https://github.com/cncf/glossary/pull/3241
> [FR] update horizontal scaling

- content/fr/stateless-apps.md
Update stateless app in French following https://github.com/cncf/glossary/pull/3295
Update stateless app in French following https://github.com/cncf/glossary/pull/3295
> [FR] Update stateless app

- content/zh-cn/_index.md
sync info from content/en/_index.md to content/zh-cn/_index.md
> sync en changes to zh-cn version

- content/fr/nodes.md
- content/fr/service-proxy.md
French: fix plate-forme -> plateforme
> [FR] fix plate-forme -> plateforme

- content/fr/abstraction.md
- content/fr/function-as-a-service.md
- content/fr/serverless.md
> [FR] fix quotes

- content/en/_index.md
- content/en/contribute/_index.md
- content/en/contributor-ladder/_index.md
- content/en/style-guide/_index.md
Update the contribution info to make it easier and clearer for contributors. 
none
> simplify contributions

- LOCALIZATION.md
- README.md
- content/en/_index.md
- content/en/contribute/_index.md
- wordlist.txt
- Update the maintainers list and README
- ref. #3431
> Update the maintainers list and README

- CODEOWNERS
- Add myself (@Okabe-Junya ) to maintainers team
- Remove @castrojo from mantainers team
- Due to his busy
- Thank you for important contribution, @castrojo 
- ref: #3431
> Chore: Update CODEOWNERS

- CODEOWNERS
https://github.com/kumarankit999 is no longer exist and now CODEOWNERS file is invalid, so let me cleanup
> Cleanup CODEOWNERS

- content/en/platform-engineering.md
Added new term Platform Engineering by creating new .md file.
https://github.com/cncf/glossary/issues/3130
> [EN] add Platform Engineering

- i18n/ko.toml
This PR updates Korean UI strings, especially those in the 'Tags' page.
> [ko] Update Korean UI strings

- .github/settings.yml
- CODEOWNERS
@annalisag-spark decided to step down (and will be greatly missed 🥇)
@matteobisi and @SaraTrap have been promoted to approvers 🥳 
N/A
> Update dev-it approvers

- content/it/site-reliability-engineering.md
IT localization udpdate of SRE page
#3108 
> [it] update-sre-#3108

- CODEOWNERS
- Update CODEOWNERS to initialize vi l10n
ref. #3458 
> Update CODEOWNERS to initialize vi l10n

- .github/labeler.yml
- CODEOWNERS
Update dev-vi to apply recent settings
- #3460
- #3464
- #3458
- #3461
> Update dev-vi to apply recent settings

- content/vi/contributor-ladder/_index.md
Add Vietnamese translation for Contributor Ladder
> [vi] add Vietnamese translation for Contributor Ladder

- content/vi/security-chaos-engineering.md
Add Vietnamese translation for Security Chaos Engineering
> [vi] Localize for Security Chaos Engineering

- content/vi/cloud-native-apps.md
Add Vietnamese localization for cloud-native apps
> [vi] Localize for Cloud native apps

- content/es/style-guide/_index.md
> fix: broken `Definición` hash link 

- content/vi/containerization.md
- content/vi/virtual-machine.md
Translated the Markdown content of the "Container" page from English to Vietnamese.  
The translation preserves the original Markdown structure and ensures natural, grammatically correct Vietnamese, written in the tone of a technical blog post for Vietnamese readers.
resolves #container-vietnamese-translation
- [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: git commit -s) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your gitconfig by running git config --global alias.ci "commit -s"
> [vi] add Vietnamese localization for Containerization concept

- content/vi/cloud-computing.md
Add Vietnamese localization for cloud computing
> [vi] Localize for Cloud computing

- content/vi/_index.md
- update index page up to date.
- add Vietnamese contributors to ack (named contributors are based on commits or reviews for Vietnamese contents)
NONE
> [vi] Update index page with acknowledgement to Vietnamese contributors

- content/de/canary-deployment.md
Fixing typo according to #2106
#2106
> [de] fix typo in canary deployment page

- content/vi/containerization.md
- content/vi/virtual-machine.md
Update translation for titles: Virtual Machine & Containerization
NONE
> [vi] update translation for titles: Virtual Machine & Containerization

- content/vi/cluster.md
Add translation for cluster
NONE
> [vi] add translation for cluster

- content/bn/digital-certificate.md
- content/en/digital-certificate.md
- content/es/digital-certificate.md
- content/ru/digital-certificate.md
Update the status of the term 'Digital Certificate' to 'Completed' so that the term gets displayed for English and other localizations.
https://github.com/cncf/glossary/pull/3484#issuecomment-2858000984
> Update the status of 'Digital Certificate' to 'Completed'

- content/it/transport-layer-security.md
TLS Term transformed into Transport Layer Security, page and title renamed, "cosa è" removed, tag addedd
#3110 
> [it] update-tls-term-#3108

- content/vi/zero-trust-architecture.md
Add vietnamese localization for content zero-trust-architecture
> [vi] add translation for zero-trust-architecture

- content/en/contribute/_index.md
- content/en/style-guide/_index.md
In the "How to Contribute" and "Style Guide" pages, when mentioning semantic line breaks, there was a caveat that said "one sentence per line". But this can be misleading. Semantic line breaks do not necessarily mean "one sentence per line". Instead, here is the Semantic Line Breaks Specification (SemBr) from https://sembr.org :
1. Text written as plain text or a compatible markup language MAY use semantic line breaks.
2. A semantic line break MUST NOT alter the final rendered output of the document.
3. A semantic line break SHOULD NOT alter the intended meaning of the text.
4. A semantic line break MUST occur after a sentence, as punctuated by a period (.), exclamation mark (!), or question mark (?).
5. A semantic line break SHOULD occur after an independent clause as punctuated by a …
> Update descriptions for semantic line breaks in "How to Contribute" and "Style Guide" pages

- content/en/cluster.md
- content/en/distributed-systems.md
- content/en/nodes.md
Update the term cluster to be more precise and not contain wrong or misleading information. 
#2210
> [EN] update Cluster

- content/vi/stateless-apps.md
Add Vietnamese translation for Stateless Apps concept
> [vi] Add Vietnamese translation for Stateless Apps concept

- content/vi/policy-as-code.md
Add Vietnamese localization for Policy as Code
> [vi] Add Vietnamese localization for Policy as Code concept

- content/vi/platform-as-a-service.md
Add Vietnamese translation for Platform as a Service (PaaS)
> [vi] Add Vietnamese translations for Platform as a Service (PaaS)

- content/vi/loosely-coupled-architecture.md
Add Vietnamese translation for Loosely Coupled Architecture
> [vi] Add Vietnamese translation for Loosely Coupled Architecture

- content/vi/immutable-infrastructure.md
> [vi] Add Vietnamese localization for Immutable Infrastructure

- content/vi/stateful-apps.md
Add Vietnamese translation for Stateful Apps
> [vi] Add Vietnamese translation for Stateful Apps

- content/vi/continuous-delivery.md
Add Vietnamese localization for Continuous Delivery concept
> [vi] Add Vietnamese localization for Continuous Delivery concept

- content/it/observability.md
IT localization update, observability
#3103 
> [it] update-observability-term-#3103

- content/en/service-mesh.md
- wordlist.txt
Follow up to https://github.com/cncf/glossary/pull/3474
This work was authored by @Sonichigo, I've just reconstructed it here as I made a mess of the original PR. Sorry about that.
Deploy preview: https://deploy-preview-3511--cncfglossary.netlify.app/service-mesh/
This pull request enhances the documentation for service meshes by introducing and elaborating on the concept of sidecarless service mesh architecture. The changes highlight the differences between traditional sidecar-based models and sidecarless approaches, emphasizing their impact on resource efficiency, scalability, and performance.
* Added a new section titled "Implementation Models" to explain the traditional sidecar container model and its limitations, such as increased CPU/memory overhead and operational complexity as the …
>  [EN] update Service Mesh

- content/vi/infrastructure-as-code.md
> [vi] Add Vietnamese translation for Infrastructure as Code

- content/vi/infrastructure-as-a-service.md
> [vi] Add Vietnamese translation for Infrastructure as a Service

- content/vi/continuous-integration.md
Add Vietnamese localization for Continuous Integration concept
> [vi] Add Vietnamese localization for Continuous Integration concept

- .github/settings.yml
- CODEOWNERS
Cherrypick https://github.com/cncf/glossary/pull/3530
> [Cherrypick] Replace TR l10n approvers

- content/tr/role-based-access-control.md
> Add Turkish localization for role-based-access-control.md

- content/tr/devsecops.md
Turkish localization for DevSecOps page.
> feat: Add Turkish localization for devsecops.md

- content/en/operator.md
- wordlist.txt
Introduce Kubernetes Operator Term
#446 
> Kubernetes Operator

- content/vi/gitops.md
> [vi] Add translation for GitOps

- content/vi/role-based-access-control.md
> [vi] Add translation for RBAC
