cncf/glossary

style-guide.md

Closes #6 
I added some extra categories. I would love feedback on formatting.

First pass for the style guide

---

spellcheck.yml
wordlist.txt

Ignore casing during spell checks to reduce list of allowed words.

chore: Ignore casing during spell checks

---

style-guide.md

Tried to make the fact that "properties" don't need the last two sections a little more clear. Right now it's easy to miss.

Style guide update

---

LOCALIZATION.md

This PR adds LOCALIZATION.md file for a l10n initiation guide.
This work is based on the request from @CathPag https://github.com/cncf/glossary/pull/251#discussion_r753228798.

Add LOCALIZATION.md file for l10n initiation guide

---

CODEOWNERS

Introduced a bug where emeritus maintainers were marked as codeowners.

Remove emeritus maintainers

---

.github/workflows/spellcheck.yml

Hello,
I have just [released 0.19.0 of the GitHub Spellcheck Action](https://dev.to/jonasbn/releases-0190-of-spellcheck-github-action-a-security-release-599k) and I noticed that older versions of the Docker image had been pulled from DockerHub recently. 
I was able to locate your configuration via [SourceGraph](https://sourcegraph.com/github.com/cncf/glossary/-/blob/.github/workflows/spellcheck.yml), so I am providing you with a PR proposing an update to a more contemporary version.
It should be backwards compatible even though a lot has happened, but if you experience any issue with the PR please let me know and I will comply.
Take care and stay safe,
jonasbn

Bumped spellcheck action to latest version (0.19.0)

---

CODEOWNERS

A task based on the issue #288 (Initiate Korean Localization Team)
This PR is to check the setting for approvers for localization contents in each `/content/language/` directory works properly.
With this setting I am going to test localization procedures of Korean l10n (`dev-ko` branch).

Add Korean approvers in CODEOWNERS

---

.github/settings.yml

This PR updates
settings.yml for `dev-ko` branch protection rule and approvers.
I am not sure this configuration works, but we can check after this PR's been merged.

Update settings.yml for dev-ko branch protection

---

.github/dependabot.yml

As promised in PR #284 I would make a separate PR for a proposal for a [Dependabot](https://github.com/dependabot) configuration.
This is the configuration I use myself, it is only aimed at GitHub Actions, since I do not know anything about your project in general.
The PR enables use of Dependabot, which will scheduled intervals will create PRs for you to review and possibly merge. Since you only have one action at this time, you will not receive many PRs from Dependabot. I must admit I like to keep the schedule on a weekly basis, but you can alter this to fit your schedule.
This is a very basic configuration, which works well for me, more [documentation](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/keeping-your-actions-up-t …

Added first shot at a Dependabot configuration

---

.github/settings.yml
CODEOWNERS

The current settings for branch protection seems not work properly.
(I think some settings of https://github.com/apps/settings are not stable yet)
This PR updates `.github/settings.yml` and `CODEOWNERS` to fix configuration on branch protection.
I also suggest following configuration for permission.
- All maintainers (admins) have push permission to all branches.
- Approvers for each localization team have push permission to corresponding development branch (e.g. `dev-ko`)
- but they cannot push a commit for files not related with localization contents unless an appropriate owner(reviewer) in CODEOWNERS gives an approving review.
- they cannot push a commit to `main` branch
I'v tested `https://github.com/apps/settings` with a similar configuration in another organization :) 
I hope this …

Fix configuration for branch protection

---

content/en/gitops.md
wordlist.txt

I'm taking a stab at this and I am open to any/all feedback, especially a way to simplify the "The Problem it Addresses" section. Looking forward to your comments!

Add GitOps definition draft for submission

---

content/en/load_balancer.md

[English]: Load Balancer (issue 330)

---

.github/settings.yml
CODEOWNERS

Based on l10n team initiation requests, I added [localization approvers](https://glossary.cncf.io/contributor-ladder/#localization-approvers) for each language.
(https://github.com/cncf/glossary/projects/2)
- Add Arabic approvers #326
- Add Bengali approvers #339
- Add Spanish approvers #387
- Add Portuguese approver #290
- Add Korean approver #288
**[Important]**
- All candidates need to **leave a comment** that you understood overall policy.
It is to make l10n approvers manage (merge) PRs for l10n contributions in your development branch.
Merging a PR to the `main` branch by l10n approvers is restricted.
Even if they are possible to review …

Add localization team approvers (ar bn es pt ko)

---

config.toml
content/es/_index.md
content/es/contribute/_index.md
content/es/style-guide/_index.md
i18n/es.toml

This PR is to initiate Spanish localization based on
* Issue to #387 
* https://github.com/cncf/glossary/blob/main/LOCALIZATION.md guide
Base and target branch of this PR is dev-es which is development branch for Spanish localization.
This PR includes
- [languages.es] section in config.toml
- i18n/es.toml
- Some translated documents
- Main page
- content/es/_index.md
- Others
- contribute: content/es/contribute/_index.md
- style-guide: content/es/style-guide/_index.md

 Settings and initial contents for Spanish localization

---

assets/scss/_variables_project.scss

[The Hindi font doesn't have bold](https://dev-hi--cncfglossary.netlify.app/hi/continuous_integration/) so doesn't show a unique style for the selected sidebar item. [Here is a suggestion](https://deploy-preview-463--cncfglossary.netlify.app/client_server_architecture/) of additional styles to the sidebar to accommodate fonts that don't have bold.

Stronger style for selected sidebar item

---

.github/settings.yml
CODEOWNERS

This PR is to add new Glossary approvers
@iamNoah1 and @jihoon-seo who have been actively contributed for the CNCF Glossary project. :)
The new English approvers will have write permission for all files in this Repository.
Note: @iamNoah1 and @jihoon-seo are involved in both English approver and localization approver. 
(@iamNoah1 `dev-de`, @jihoon-seo `dev-ko`)

Add new Glossary approvers

---

CODEOWNERS

This PR is just to rename the content dir to the Portuguese localization team from `content/pt` to `content/pt-br` and fix the codeowners file to get give the permissions to the right folder
After that, I'll open a PR to update the dev branch (`dev-pt`)

Rename portuguese content dir from pt to pt-br

---

content/en/cloud_native_tech.md

This PR modifies a sentence in cloud native definition clearly.
I think people who search a definition for cloud native tech may not understand what is ‘promise of the cloud’.
So, I'd like to remove ‘promise of the cloud’ and refine the sentence.

Modify a sentence in cloud native definition clearly

---

.github/settings.yml
CODEOWNERS

Ref:
- [localization approvers](https://glossary.cncf.io/contributor-ladder/#localization-approvers)
- https://github.com/cncf/glossary/projects/2
---
- Add Chinese approver #451
**[Important]**
- All candidates need to **leave a comment** that you understood overall policy.
It is to make l10n approvers manage (merge) PRs for l10n contributions in your development branch.
Merging a PR to the `main` branch by l10n approvers is restricted.
Even if they are possible to review a PR to the `main` branch and give an approval to the PR, they should not approve the PR. 
So, please do not approve if a PR is not related with your localization.
- After …

Add zh l10n team approvers

---

.github/ISSUE_TEMPLATE/new-term.yml

This PR enhances the existing issue template for a new term proposal.
with following enhancements
- auto-labeling : lang/en, new term, `triage/awaiting`
- explain triage procedure (assessment for new term proposal)
- checklist
https://github.com/seokho-son/glossary/issues/new?assignees=&labels=lang%2Fen%2Cnew+term%2Ctriage%2Fawaiting&template=new-term.yml&title=%5BNew+term%5D+%60GlossaryTermHere%60
https://github.com/seokho-son/glossary/issues/17

Update issue template for new term proposal

---

i18n/ko.toml

- Related issue: #470
- Reflected https://github.com/cncf/glossary/pull/483#issue-1149972639
- (applies L10n of Feedback section to `dev-ko` branch)
- Reflected https://github.com/cncf/glossary/pull/483#pullrequestreview-893497872
- (add indentation for the HTML)
Preview: https://deploy-preview-519--cncfglossary.netlify.app/ko/virtual_machine/#:~:text=피드백,아니오

[ko] L10n of Feedback section

---

.github/settings.yml
CODEOWNERS

Based on requests from l10n teams, I added [localization approvers](https://glossary.cncf.io/contributor-ladder/#localization-approvers) for each language.
(https://github.com/cncf/glossary/projects/2)
- Update Arabic approvers
- (invite) Ahmed Rezk (@arezk84)
- (release) Osama Nabil (@hacktron95)
- Update Spanish approvers
- (invite) Carol Valencia (@krol3)
- (release from dev-es) Catherine Paganini (@CathPag) 
**[Important]**
- All candidates need to **leave a comment** that you understood overall policy. (l10n teams: please share this message to candidates)
It is to make l10n approvers manage (merge) PRs for l10n contributions in your …

Update localization team approvers (dev-ar, dev-es)

---

i18n/pt-br.toml

Translate the feedback section to pt-BR.
Related to #675.

[pt-BR] Translate feedback section

---

.github/ISSUE_TEMPLATE/update-term.yml

This PR updates issue template for updating a term.
Based on the suggestion (adding triage process for the issue template for updating term) 
by @iamNoah1 :)

Update issue template for updating a term

---

content/es/.wordlist.txt
content/es/canary_deployment.md

feat: canary deployment

---

content/en/event-driven-architecture.md

- This PR supersedes & closes #637.
- [Removed irrelevant commits.](https://github.com/cncf/glossary/pull/637#issuecomment-1152419574)
- Squashed 3 commits from @jasonsmithio to one single commit.
- [Added missing line.](https://github.com/cncf/glossary/pull/637/files#r894446870)
- [Renamed to `event-driven-architecture.md`.](https://github.com/cncf/glossary/pull/637/files#r894456454)
- Removed hard-coded domain name. (`https://glossary.cncf.io/service/` → `/service/`)

[en] Add term: 'Event-Driven Architecture'

---

content/pt-br/vertical_scaling.md

Add 
- content/pt-br/vertical_scaling.md

Add content/pt-br/vertical_scaling.md

---

content/pt-br/versioncontrol.md

Add
- content/pt-br/versioncontrol.md

Add content/pt-br/versioncontrol.md

---

.gitignore

This PR adds `.hugo_build.lock` file to `gitignore`,
which will prevent cases like https://github.com/cncf/glossary/pull/997#issuecomment-1166452462.

Add `.hugo_build.lock` file to `gitignore`

---

config.toml

Currently the search form on PR instance redirects to the live Glossary site. This PR is to get it so that the form keeps the user on current instance.
If you go to [this dev instance](https://deploy-preview-1050--cncfglossary.netlify.app/) and search for something, you'll see the search results now appear on the same dev instance rather than going to the live site.
Signed-off-by: cjyabraham <cjyabraham@gmail.com>

Get Search working on PR instance

---

LOCALIZATION.md

Signed-off-by: Bishal Das <70086051+bishal7679@users.noreply.github.com>

Fixed `block after the should` be outside backticks

---

content/en/virtualization.md

Link to the virtual machine in the glossary when reading about it and Modify the documentation by adding a link to cloud computing to understand the example given in a better way.
Signed-off-by: KiranSatyaRaj <90622705+KiranSatyaRaj@users.noreply.github.com>

Link "virtual machine" and  "cloud computing"

---

wordlist.txt

Added "multitenancy".  Along with multi-tenancy, this is a common speling (e.g. https://en.wikipedia.org/wiki/Multitenancy)
Signed-off-by: Sergey Borovoy <48699431+sergeyborovoy@users.noreply.github.com>

Update wordlist.txt to add multitenancy

---

content/en/container-image.md

Add missing links

---

config.toml
content/fr/_TEMPLATE.md
content/fr/_index.md
content/fr/contribute/_index.md
content/fr/style-guide/_index.md
i18n/fr.toml

This PR is to initiate French localization based on:
* Issue #915
* https://github.com/cncf/glossary/blob/main/LOCALIZATION.md Guide
Base and target branch of this PR is `dev-fr` which is development branch for French localization.
This PR includes:
* `[languages.fr]` section in `config.toml`
* `content/fr/` directory
* `i18n/fr.toml`
* Some translated documents:
* Main page: `content/fr/_index.md`
* contribute: `content/fr/contribute/_index.md`
* style-guide: `content/fr/style-guide/_index.md`
* Others:
* FR Template: `content/fr/_TEMPLATE.md`
Since French localization team owns content/fr/* only,
this PR will require approvals from upstream owners (maintainers).

Settings and initial contents for French localization

---

.github/settings.yml
CODEOWNERS

Given his active [collaboration](https://github.com/cncf/glossary/pulls?q=author%3A92nqb) in Spanish localization team, this PR recognizes the effort made by @@92nqb and promotes him to the approver role.
/cc @raelga @krol3

Add Nicolas Quiceno to Spanish approver team

---

content/en/kubernetes.md

Made some edits so it's easier to understand but still have open questions. Some sentences don't make 100% sense to me (please view comments below)
NA
- [ x] This PR does not contain plagiarism
- [ x] I have signed off on all commits 

Kubernetes edits + open questions

---

content/en/cloud-computing.md

adding primary service models to the documentation and modifying it for a better understanding and readability.
Signed-off-by: Kiran Satya Raj <90622705+KiranSatyaRaj@users.noreply.github.com>

Add service models and modify documentation

---

.github/workflows/labeler.yml

- This PR is to update labeler workflow (automate labeling PRs)
- https://github.com/actions/labeler#create-workflow
- The labeler workflow has been disabled to check a security issue within the labeler workflow. (a high level permission given to the `pull_request_target` option)
- According to some valuable discussions with @yunkon-kim , we concluded that the concern with the permission issue can be minimized. (please review and discuss if there is any other concern)
- NA …

Enable labeler workflow

---

.github/ISSUE_TEMPLATE/new-term.yml

Small but meaningful improvement. Before adding a new issue it should be also checked if the term was not already proposed but declined.

add check if the term has already been declined in the past

---

.github/settings.yml
CODEOWNERS

- Request for #1310
- [Contributor-ladder: localization approvers](https://glossary.cncf.io/contributor-ladder/#localization-approvers)
- All candidates need to **leave a comment** in this PR that you understood the following policies and information. (l10n teams: please share this message to candidates)
- [Policies for localization approvers (to be confirmed by candidates)](https://github.com/cncf/glossary/discussions/723)
- Please understand that a candidate who does not check and confirm it, the candidate can not be an approver.
It is to make l10n approvers manage (merge) PRs for l10n …

Add Urdu Localization Team Approvers

---

content/ko/_TEMPLATE.md

Disable TEMPLATE from sidebar of Korean site.
Status: Completed makes the TEMPLATE item shown in the sidebar 
N/A

Disable TEMPLATE from sidebar of Korean site

---

.github/pull_request_template.md

Signed-off-by: Noah Ispas (iamNoah1) <noahispas@gmail.com>
Add info about adding sign off to global git config 
none

add info about adding sign off to global git config

---

content/pt-br/shift-left.md

Localization shift-left.md to pt-br

Add content/pt-br/shift-left.md

---

content/es/auto-scaling.md

This change synchronizes the changes made on the `auto-scaling` term to the Spanish version.
NA

Update auto-scaling term

---

.github/workflows/check-outdated-terms.yaml
.github/workflows/post-outdated-terms-report.yaml

Signed-off-by: Yunkon Kim <hermitkim1@gmail.com>
- This PR will add 2 workflows to check outdated terms.
- check-outdated-terms.yaml
- post-outdated-terms-report.yaml
- The check-outdated-terms workflow has the following steps:
1) Set up environment variables for the target L10n team
2) Checkout
3) Check outdated
4) Upload output
- The post-outdated-terms-report has the following steps:
1) Show the github context (temporarily for debug)
2) Download output
3) Set up environment variables from the output
4) Generate a report markdown
5) Create an issue from the report (with outdated, good first issue, and lang/xx labels)
- An example of report: https://github.com/yunkon-kim/test-on-github-actions/issues/98
<p align="center">
</p>
- **For the time being, I'd like to test and troubleshoot 2 …

Add workflows to track outdated terms

---

content/de/application_programming_interface.md

Issue: https://github.com/cncf/glossary/issues/508

[localization/german] Add localization for API

---

content/es/client-server-architecture.md

This change synchronizes the changes made on the `client-server architecture` term to the Spanish version.
NA

Update client-server architecture term

---

content/en/event-streaming.md

The Event streaming definition contains an absolute reference to the API term, this exception doesn't match with the rest of the terms.

Change api absolute reference

---

content/de/blue-green-deployment.md

Localizing Blue Green Deployment 
https://github.com/cncf/glossary/issues/511 

[DE] Localization of Blue Green Deployment

---

content/es/.wordlist.txt
content/es/platform-as-a-service.md

Adding the description of PaaS in spanish.
Resolves #1400 

 [Spanish] localize 'Platform as a Service (PaaS)' #1400

---

.github/settings.yml
CODEOWNERS

- Update dev-it approvers
Based on the following request from the Italian team.
- https://github.com/cncf/glossary/pull/1414
- https://github.com/cncf/glossary/pull/1414#issuecomment-1298321548
(ref: @annalisag-spark)
- All new candidates need to **leave a comment** in this PR that you understood the following policies and information. (l10n teams: please share this message to candidates)
- [Policies for localization approvers (to be confirmed by candidates)](https://github.com/cncf/glossary/discussions/723)
- Please understand that a candidate who does not check and confirm it, the candidate can not be an approver.
- The approvers of l10n team will have a push …

Update dev-it approver

---

.github/settings.yml
CODEOWNERS

- Update dev-de approvers
Based on the following request from the German team.
- https://github.com/cncf/glossary/pull/1461  (ref: @iamNoah1)
- All new candidates need to **leave a comment** in this PR that you understood the following policies and information. (l10n teams: please share this message to candidates)
- [Policies for localization approvers (to be confirmed by candidates)](https://github.com/cncf/glossary/discussions/723)
- Please understand that a candidate who does not check and confirm it, the candidate can not be an approver.
It is to make l10n approvers manage (merge) PRs for …

Add bcubk as German localization approver

---

content/en/hypervisor.md

adding the term hypervisor to the glossary
Signed-off-by: Kiran Satya Raj <90622705+KiranSatyaRaj@users.noreply.github.com>

Add content/en/hypervisor

---

content/en/digital-certificate.md

Signed-off-by: Michael <cloudyonspring@126.com>
- Remove extra blank lines 
- Remove a redundant heading
- Tweak long lines

Update layout and remove redundancy in digital-certificate.md

---

i18n/pt-br.toml

Signed-off-by: Ana Cunha <1771610+anacunha@users.noreply.github.com>
[Portuguese] Translate i18n strings to use tags #1048 
Changed translation from `"todos"` to `"todas"` as it is meant to be used in sentences such as `"All Tags"`, which translates better to `"Todas Tags"`

[ptbr] Translate i18n strings used in tags

---

.github/workflows/labeler.yml

The labeler task helps to organize PR based on the folder where the changes happen. This logic needs to be applied to all languages.

Enable labeler to non-korean languages

---

content/en/debugging.md

Oops, we said we would deprecate but looks like I forgot to add it to the PR. 
- [ x] This PR does not contain plagiarism
- [ x] I have signed off on all commits 

Deprecating debugging

---

content/en/containers-as-a-service.md
content/en/database-as-a-service.md
content/en/debugging.md
content/en/firewall.md
content/en/managed-services.md
content/en/platform-as-a-service.md
content/en/software-as-a-service.md
content/en/version-control.md
layouts/partials/head.html
layouts/partials/page-meta-links.html
layouts/partials/taxonomy_terms_cloud.html

Fixes a few small issues with the current taxonomies:
- `draft: true` needs to be added to terms that are no longer "Completed" such as those that are now "Deprecated"; this removes them from the tag count on [this page](https://glossary.cncf.io/tags/) and will remove them from the google search index
- changed 2 instances of the "fundamentals" tag to be "fundamental" which is more common
- removed a "Deprecated" tag that was only used in one instance
- made terms title-case on [this page](https://glossary.cncf.io/tags/) to agree with all other instances
- reference to google_news internal template is removed since it is deprecated
- new way of getting .Path is implemented to prepare for upcoming change in Hugo

Fix taxonomy issues

---

assets/scss/_header.scss

Inserts an active indicator on topnav elements to align with other CNCF sites like [Contribute](https://contribute.cncf.io/maintainers/):

Get active indicators working on topnav

---

content/en/kubernetes.md

MD code for containers and cloud-computing has wrong address (missing a / in each one).
Signed-off-by: Adail Horst <the.spaww@gmail.com>
- [X ] This PR does not contain plagiarism
- [X ] I have signed off on all commits 

Correct 2 URLs

---

content/pt-br/kubernetes.md

Signed-off-by: Adail Horst <the.spaww@gmail.com>
Update kubernetes translation to pt-br
Issue #813

Issue 813 - Kubernetes to PT-BR

---

.github/workflows/check-outdated-terms.yaml

Signed-off-by: Yunkon Kim <hermitkim1@gmail.com>
- This PR will update the workflow to check outdated terms to fix bugs. (check-outdated-terms.yaml)
- Fix the failure to create a diff log file
- Avoid creating empty diff log files
- Check if the branch name is 'dev-ko' (currently it is testing)
#1682, #1360

Update the check outdated terms workflow

---

content/pt-br/function-as-a-service.md

Add FaaS description in Portuguese
resolves #1207 
- only copy other people's work if you are quoting and contributing it to them.
- [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you work locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

Add FaaS description in Portugese

---

content/de/client-server-architecture.md

localize client server architecture
#513

513 german localize client server architecture

---

.github/workflows/stale.yml

This change fixes the syntax of stale workflow, removing the double quotes from the name and upgrades the version number of the task
NA

Fix dev-es stale GH workflow

---

content/ko/container-as-a-service.md

https://github.com/cncf/glossary/blob/main/content/en/containers-as-a-service.md has been deprecated. by https://github.com/cncf/glossary/pull/1449
This PR deprecates the Korean version too.
None

[ko] Deprecate Korean container-as-a-service.md

---

content/ko/debugging.md

https://github.com/cncf/glossary/blob/main/content/en/debugging.md. 
by https://github.com/cncf/glossary/pull/1449
This PR deprecates the Korean version too.
None

[ko] Deprecated Korean debugging.md

---

.github/settings.yml
CODEOWNERS

Given his active collaboration in French localization team, this PR recognizes the effort made by @sestegra and promotes him to the approver role.
NA

Add sestegra as an fr approver

---

.github/settings.yml
CODEOWNERS

Add initial approvers for Traditional Chinese based on the initiation request (#1987)
- [A] Ader Fu (@ydFu)
- [A] Phil Huang (@pichuang)
#1987

Add initial approvers for Traditional Chinese

---

i18n/es.toml

This change translates the missing tags section located in the Spanish i18n file
Similar to https://github.com/cncf/glossary/pull/1748

[es] Translate tags section in es.toml file

---

.github/labeler.yml

Update labeler.yml to add lang/tw and lang/ja
none

Update labeler.yml to add lang/tw and lang/ja

---

.github/settings.yml

1. Add initial approvers for Japanese Localization based on the initiation request (#1422)
- [A] Kohei Ota (@inductor)
- [A] Nao Nishijima(@naonishijima)
- [A] Kaito (@kaitoii11)
2. Change permission for @iamNoah1 @jihoon-seo from maintain to admin so that the maintainers can merge a PR related with branches 
3. Remove inactive localization approvers
#1422

Update permission and add initial approvers for Japanese

---

content/es/auto-scaling.md
content/es/horizontal-scaling.md
content/es/vertical-scaling.md

- added `es/vertical-scaling.md`.
- updated references in `auto-scaling` & `horizontal-scaling` terms.
- resolves #1782 

[ES] content/es/vertical-scaling.md

---

.github/settings.yml
CODEOWNERS

Adding myself to the en reviewers group.
Adding myself to the system that (i think) automatically sets reviewers for lang/en PRs
n/a

Adding nate-double-u to list of en approvers

---

content/en/_index.md

I've seen contributors struggle with joining the glossary's Slack channel via link.
(for example) #glossary-localization-korean: https://cloud-native.slack.com/archives/C02PC0MLQKU
In that case, we had to manually add them using the Slack channel's "Add People" feature.
So what I did is, a solution for contributors to join the CNCF Slack workspace first on the link, https://communityinviter.com/apps/cloud-native/cncf.
This could be a way for contributors to join Glossary using only a guide.
Resolves #2082  …

Added a procedure to join the CNCF Slack workspace on main page

---

content/fr/scalability.md

This PR localizes scalability concept to French
resolves #1840 

Traduction de scalability.md

---

content/fr/vertical-scaling.md

Localize `Vertical Scaling` in French
#1998 

[fr] Localize vertical scaling

---

.github/settings.yml
CODEOWNERS

This PR update .github/settings.yml and CODEOWNERS to invite @castrojo as an approver for English content in this Repo.
Based on maintainers' decision. :)
None

Add `castrojo` to the list of English approvers

---

content/fr/microservices-architecture.md

This PR localizes Microservice-architecture to French
Resolves https://github.com/cncf/glossary/issues/2115

[FR] localization of Microservice-architecture

---

config.toml
i18n/tr.toml

- Added a section in `config.toml` for Turkish
- Added a `i18n/tr.toml` file for the common UI text translation
Google Docs for reference:
- [`i18n/tr.toml`](https://docs.google.com/document/d/1iiKTIeUz1UZouRIiLZfE6CFBGorXV6elcb-O5fkYNQ0/edit)
- [`config.toml`](https://docs.google.com/document/d/10i4QtWh_OMBkDHs0CI4JT82mLzOT1PTraks_IXoetHc/edit)
Preview: https://deploy-preview-2235--cncfglossary.netlify.app/tr/
(all empty right now)
- [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your …

[tr] Add website config for Turkish

---

.github/settings.yml

`sestegra` is missing for merging into dev-fr branch
N/A

Add missing sestegra for merging into dev-fr

---

CONTRIBUTING.md
LOCALIZATION.md
README.md
assets/json/offline-search-index.json
content/en/container-orchestration.md
content/en/edge-computing.md
spin-new-glossary.md

This PR fixes some minor whitespace issues (e.g., spacing around a Markdown heading, a few trailing quotes in non-primary content), as well as fixes one typo in repo guidance and one in a trivial comment.
From a consistency perspective, almost all of the primary content in `content/en/` uses spacing around Markdown headers (and most Markdown linters recommend that), so I just found a few which were lacking it so made them consistent.
Just minor editorial tweaks!
As always, love referring to this content; thanks for contributing it! …

chore: Fix whitespace and a few trivial typos

---

content/en/idempotence.md

The last sentence was ambiguous: "If the parameters are the same, an idempotent operation won't affect the application it calls." 
it's not clear who calls who, and who is not affected.
I changed it to:
"If the parameters are the same, executing an idempotent operation several times will have no additional effect."
Do you think we should add an example like adding zero to a number or the elevator call button that you can click any number of times?
https://github.com/cncf/glossary/pull/2212#issuecomment-1638194216  …

[EN] update idempotence

---

.github/workflows/check-outdated-content.yaml

This change fixes some types and enables the Check outdated terms in the `dev-es` branch
NA

Enable check outdated gh action in dev-es

---

.github/labeler.yml

- This PR will update path pattern in `.github/labeler.yml`.
- For example, `content/ko/*` changes to `content/ko/**`.
- This is required to include subdirectories in the labeling target.
See this [basic example from actions/labeler](https://github.com/actions/labeler#basic-examples)
> ```
> # Add 'label1' to any changes within 'example' folder or any subfolders
> label1:
> - example/**
> 
> # Add 'label2' to any file changes within 'example2' folder
> label2: example2/*
> 
> # Add label3 to any change to .txt files within the entire repository. Quotation marks are required for the leading asterisk
> label3:
>- '**/*.txt'
>```
- Ref. #2278 
- When I created a PR for updating `content/ko/contribute/_index.md`, the github-actions `bot` removed the label from the PR.
- don’t copy other …

Update path pattern in `.github/labeler.yml`

---

config.toml

The language name for Traditional Chinese is currently `繁體中文(Traditional Chinese)` (without a space in between). Usually we would put a space before parentheses, so it looks prettier.

Add a space in the language name of Traditional Chinese

---

content/en/runtime.md
wordlist.txt

Added a new term - Runtime
resolves #1892 

[EN] add Runtime

---

content/en/ebpf.md
wordlist.txt

Added a new term - eBPF
Resolves #1448

[EN] add eBPF

---

content/tr/abstraction.md

Localize "Abstraction" page into Turkish

[tr] Update content/tr/abstraction.md

---

content/en/devsecops.md

- Add `Continuous Delivery` & `Continuous Deployment`
- Fixed error links
- Fixed grammar `organization's`
resolves #2167 

[EN] `DevSecOps` fixed error links & grammar

---

content/es/auto-scaling.md
content/es/bare-metal-machine.md
content/es/cloud-computing.md
content/es/cloud-native-apps.md
content/es/container-image.md
content/es/continuous-delivery.md
content/es/devops.md
content/es/horizontal-scaling.md
content/es/hypervisor.md
content/es/immutable-infrastructure.md
content/es/infrastructure-as-a-service.md
content/es/infrastructure-as-code.md
content/es/kubernetes.md
content/es/loosely-coupled-architecture.md
content/es/microservices-architecture.md
content/es/mutual-transport-layer-security.md
content/es/nodes.md
content/es/platform-as-a-service.md
content/es/scalability.md
content/es/stateful-apps.md
content/es/style-guide/_index.md

Since not all the glossary terms were available at the same time, contributors deferred from referencing terms in Spanish. Now, that we have the majority of terms translated we need to update those to the correct ones.
For the record this can be easily spotted with the following grep expressions:
```sh
grep -PHnro "\[.*?\].*?\(/.*?\)" content/es | grep -v '(/es/'
```
I double checked that each referenced `/es` term exist, however, there are 2 "special" cases I need to bring to your attention:
1. I had omitted the SaaS term since it's deprecated and its references were removed in main branch already [PR](https://github.com/cncf/glossary/pull/2198) & [commit](https://github.com/cncf/glossary/commit/1d461662ae35c8d1d3b13eb87f42e8be2835143c#diff-e39259e7b9696cdc87944e88a1a570ab38112e4d782c4e3f …

Update Spanish reference links

---

content/en/_index.md
content/en/contribute/_index.md

Removing Catherine as maintainer mentions

Removing Catherine maintainer mentions

---

.github/settings.yml
CODEOWNERS
LOCALIZATION.md
README.md
content/en/_index.md
content/en/contribute/_index.md

This PR updates overall ownership and emeritus state. (collected all recent requests)
Based on #2268 and Slack & Monthly meeting consensus. 
- Move @CathPag and @JasonMorgan to emeritus maintainer.
- Remove @CathPag and @JasonMorgan from the codeowner so that they are not notified for review. (but, they have still authority to merge PRs)
> Seokho Son
> A simple thank you doesn't seem fitting for [@Catherine](https://cloud-native.slack.com/team/U5U4E68P4). In fact, she's the main maintainer who led and sphread the Glossary project, and friend who "dragged" me in here. On behalf of all Glossary contributors and Cloud Native users, I want to say a huge, huge thank you! 
> Also, I would like to keep Catherine as an emeritus maintainer, someone we can occasionally turn to for advice as she …

Update ownership and emeritus state

---

.github/settings.yml
CODEOWNERS

In recognition of @guillaumebernard84's dedicated contributions to the French localization team, this PR elevates him to the role of approver.
N/A

Add @guillaumebernard84 as an fr approver

---

.github/auto-comment-config.yaml
.github/workflows/auto-comment.yml

This PR add a Workflow that automatically add a comment based on labels.
- Requested feature from the latest CNCF Glossary Working Group meeting.
https://docs.google.com/document/d/1kjNrLWbMHSQ3x4ob8Q_lNOoJ4f8uPQcuD9a0Sif24NY/edit?pli=1
> Add an automation for every incoming PR that says something like: “To see where this is in the review pipeline and follow the progress, please have a look at the [project board](https://github.com/orgs/cncf/projects/26)”
- [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could …

Add a Workflow that automatically add a comment based on labels

---

.github/workflows/es-spellcheck.yml
.github/workflows/spellcheck.yml

Initial merging the dev-tw branch into main branch
Task: Update dev-tw based on the latest main.
#2355

Sync branch dev-tw from main(20231011)

---

content/zh-tw/abstraction.md

We currently have different translations for the term property -- `特性` and `屬性`. Based on the discussion in https://github.com/cncf/glossary/pull/2496#discussion_r1359176797, we'd like to unify the translation as the latter.
resolves #2505

[tw] Unify the translation for the term `property`

---

layouts/partials/footer.html

Updating the Twitter logo in the footer to X (as well as the URL to the CNCF Twitter page)
Part of updating all CNCF sub-sites - https://github.com/cncf/cncf.io/issues/769

Updating Twitter logo to X

---

.github/settings.yml
CODEOWNERS

Add a new approver for Russian based on a requested by the localization team.
- [A] Timur Tukaev (@tym83)
- Requested by the Russian localization team: https://cloud-native.slack.com/archives/C05G46RMQTX/p1698057198264159?thread_ts=1698038167.603209&cid=C05G46RMQTX

Add additional approver for Russian

---

.github/settings.yml
CODEOWNERS

Add a new approver for Hindi based on a requested by the localization team.
- @abhay-raj19
- @aj11anuj
- @kumarankit999
- @bishal7679
Step down approvers for Hindi based on a requested by the localization team.
- @anubha-v-ardhan 
- @sayantani11 
Thanks to @anubha-v-ardhan @sayantani11 for their valuable contributions so far.
Welcome new localization approver candidates.
- Please note that 
We are going to temporarily increase the maximum number of approvers (so far, it is upto 5 but extend to 6 approvers) and later adjust based on future activities. It is an exceptional case aimed at bolstering the team and only focused on their willingness. 
- https://cloud-native.slack.com/archives/C02PCHEQXK6/p1698053643317859?thread_ts=1696474323.614059&cid=C02PCHEQXK6
- don’t copy other people’s …

Update approvers for Hindi localization

---

.github/settings.yml
CODEOWNERS

I'm stepping down from my role in the Turkish glossary team since I was not an active member of the community so I believe @rwxdash will be more active than I'm. 

Replace developer-guy with rwxdash as TR approver

---

content/tr/container.md

- Added Turkish localization for container.md
- [`container.md`](https://docs.google.com/document/d/1UIys2CdfXAHYSEmv8lXC5UxLTLQO-sewUCekhP_c7Xw)

[tr] Add Turkish localization for container.md

---

content/zh-tw/mutual-transport-layer-security.md

Origin content from https://glossary.cncf.io/mutual-transport-layer-security/
resolves #2565 

[tw] Localize `mTLS` for Traditional Chinese

---

content/en/vertical-scaling.md

According to the guidelines outlined in the style guide: `When used in your definition, always link to existing glossary terms (only the first mention should be hyperlinked).` 
In light of this, I have identified two instances of repeated hyperlinks to "horizontal scaling" within this article. Consequently, I have initiated this pull request to eliminate the redundant links, thereby maintaining the overall conciseness of the article.
CNCF Style Guide:
https://glossary.cncf.io/style-guide/#keeping-it-simple …

[en] Update Vertical Scaling

---

content/en/cloud-native-tech.md

Since the style guide encourages links to existing glossary terms, I think linking to the Loosely Coupled Architecture will be helpful here.

[en] Add a link in cloud-native-tech.md

---

wordlist.txt

Issue #2679 mentions some keywords that were added previously when spellcheck workflow was not active. Now the checks are failing.
Adding the keywords should fix the Github spellcheck workflow.
resolves #2679 

Add keywords to wordlist.txt failing spellcheck

---

content/en/stateful-apps.md
content/en/stateless-apps.md
wordlist.txt

Stateless statefull update noah

---

content/ja/pod.md

Localize Pod for Japanese
resolves #2718 

[ja] Localize Pod for Japanese

---

content/fr/transport-layer-security.md

[FR] Localize `Transport Layer Security (TLS)`
Resolves https://github.com/cncf/glossary/issues/2639

[FR] Localize `Transport Layer Security (TLS)`

---

.github/labeler.yml
.github/workflows/labeler.yml

- we recently upgraded the version of labeler workflow, but the v5 includes breaking changes.
- this PR tries to fix the error incorporated from the labeler v5 based on https://github.com/actions/labeler?tab=readme-ov-file#breaking-changes-in-v5
- workflow error: https://github.com/cncf/glossary/actions/runs/7359637719/job/20034694686?pr=2760
```
The configuration file (path: .github/labeler.yml) was not found locally, fetching via the api
Error: Error: found unexpected type for label 'lang/ar' (should be array of config options)
Error: found unexpected type for label 'lang/ar' (should be array of config options)
```
- [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verifi …

Fix labeler workflow error

---

content/fr/mutual-transport-layer-security.md

Correction of a dead link
Updated the link with the good filename
resolves #2783 

[FR] Fix link in `mutual-transport-layer-security.md`

---

layouts/_default/baseof.html
layouts/partials/head.html

To allow us more flexibility we want to install GTM in place of just GA4. We will also be including a HubSpot tracking code using GTM. See https://github.com/cncf/cncf.io/issues/823

Installs GTM instead of just GA4

---

.github/ISSUE_TEMPLATE/new-term.yml

When opening an issue, there was only a link to the glossary to check if suggested terms already exist. But we also have terms that are not finished, thus not show up in the glossary. Contributors who open an issue for a new term should also check there and create an issue to update the term instead of an issue to add the term. 
none

add info about not completed terms

---

.github/settings.yml
CODEOWNERS

Add a new approver for Japanese Localization team
- [A] Junya Okabe (@Okabe-Junya)
Slack link: https://cloud-native.slack.com/archives/C057F81GFUG/p1705327504026509

Add additional approver for Japanese Localization team

---

content/ja/_index.md

There was a typo in the contributor's name. The name `yuichi-nakamura` san was mistakenly written as `yuishi-nakamura`. This typo has been corrected.
no issue related to this PR

[ja] hotfix: fix typo in Initial localization contributors list

---

content/fr/event-driven-architecture.md

Localize Event-Driven Architecture
Resolves https://github.com/cncf/glossary/issues/2815

[FR] Localize Event-Driven Architecture

---

content/fr/edge-computing.md

Localize  Edge Computing in French
resolves https://github.com/cncf/glossary/issues/2887

[FR] Localize Edge Computing

---

content/en/tightly-coupled-architecture.md

This PR fixes the filename and the page title for tightly coupled architecture.
This matches Title in 'loosely coupled architecture'
- [x ] This PR does not contain plagiarism
- [x ] I have signed off on all commits 

[EN] update Tightly Coupled Architecture

---

content/en/container-orchestration.md
content/en/containerization.md
content/en/continuous-delivery.md
content/en/virtual-machine.md

Since the style guide encourages links to existing glossary terms, I think all these interlinks in containerisation, virtualisation, and CI/CD are helpful.
It also brings a bit more consistency. E.g., for now, the Continuous Deployment text links to Continuous Delivery and  Continuous Integration, but the Continuous Delivery text doesn't do it.

[en] More interlinking for containerisation & virtualisation

---

LOCALIZATION.md
config.toml

As discussed before (see the issue below), ordering the localisations in the top-right menu seems a good idea. However, while implementing it, I realised that sorting localisations written in various languages can be quite tricky.
Based on [this ICU demo](https://icu4c-demos.unicode.org/icu-bin/locexp?_=en_US&d_=en&x=col) and some common sense (e.g. looking at how Google sorts the languages in its interfaces), I ended up with this order for existing languages:
- English (should be always first anyway)
- Deutsch
- Español (Spanish)
- Français (French)
- Italiano
- Português
- हिन्दी (Hindi)
- বাংলা (Bengali)
- 한국어 (Korean)  
- 简体中文 (Simplified Chinese)
- 繁體中文 (Traditional Chinese)
- اردو (Urdu)
I'll be happy to see any other thoughts on the best order (if there are any).
One last important …

Sorting existing languages in the menu

---

.github/workflows/post-outdated-content-report.yaml
content/en/ebpf.md
content/en/ingress.md

Update Term Ingress
resolves #2880 #2881

[EN] update term ingress

---

content/fr/ingress.md

Localize Ingress
resolves [#2847](https://github.com/cncf/glossary/issues/2847)

[FR] Localize Ingress

---

.gitignore
Makefile
README.md
assets/js/search.js
assets/scss/_search.scss
config.toml
content/de/search.md
content/hi/search.md
content/it/search.md
content/ja/search.md
content/ko/search.md
content/pt-br/search.md
content/tr/search.md
content/ur/search.md
content/zh-cn/search.md
content/zh-tw/search.md
layouts/_default/content.html
layouts/_default/search.html
layouts/partials/search-input.html
netlify.toml
package.json

From https://github.com/cncf/cncf.io/issues/836:
Google Custom Search doesn't seem to produce very good search results on small sites. It'd be better to remove our reliance on Google as well. Instead we can use [PageFind](https://pagefind.app/), which is an open source local search for static sites.
Current issues with GCS on the subsites:
- https://github.com/cncf/glossary/issues/755 addressed by [PageFind multilingual support](https://pagefind.app/docs/multilingual/)
- https://github.com/cncf/glossary/issues/2087
- It's not open source
- It produces poor or [no results on the smaller sites](https://tag-security.cncf.io/search/?q=disappointed#gsc.tab=0&gsc.q=disappointed&gsc.page=1)
Please [test this](https://deploy-preview-3008--cncfglossary.netlify.app/) to see if the search results …

Use PageFind for search

---

content/en/observability.md

The current link to the CNCF Landscape observability section is not working anymore. This PR updates the link to a valid one.
- Current (not working):
https://landscape.cncf.io/card-mode?category=observability-and-analysis&grouping=category
- Proposed:
https://landscape.cncf.io/?group=projects-and-products&view-mode=card#observability-and-analysis--observability
N/A

Update "Cloud Native Landscape's observability section" link

---

content/ja/event-streaming.md

Localize https://glossary.cncf.io/event-streaming/ into Japanese
Resolves #2854 

[ja] Localize Event Streaming into Japanese

---

content/en/security-chaos-engineering.md

Add Link to word "SRE" that is already in the glossary.
No issue open as it is a minor change with no impact on definition.

[EN] Update security-chaos-engineering

---

layouts/_default/search.html

Currently when you refine your search term, each additional edit get stored in the browser history so that clicking Back will only take you to the previous edit. This eliminates that storage so that clicking Back will take the user to the previous page.

Don't store search increments in the browser history

---

content/fr/security-chaos-engineering.md

Localize security chaos engineering in French
resolves #3142 

[FR] Localize Security Chaos Engineering

---

content/en/containerization.md

easier way to define containersiation.

[EN] update containerization

---

content/en/webassembly.md
wordlist.txt

[EN] add WebAssembly

---

.htmltest.yml
content/fr/container-orchestration.md

- Contributes to #3190
- Normalizes links, adding a trailing slash, as reported by the link checker
- Adds a missing link to the containerization page -- so as to match the English base language version of the page
- There are no other changes. Paragraphs were line-wrapped à la Prettier.

[fr] Enable link checking, and normalize links, add missing

---

.htmltest.yml
content/es/application-programming-interface.md
content/es/auto-scaling.md
content/es/chaos-engineering.md
content/es/cloud-native-apps.md
content/es/cloud-native-tech.md
content/es/cluster.md
content/es/container-image.md
content/es/container-orchestration.md
content/es/distributed-apps.md
content/es/firewall.md
content/es/horizontal-scaling.md
content/es/infrastructure-as-a-service.md
content/es/load-balancer.md
content/es/loosely-coupled-architecture.md
content/es/monolithic-apps.md
content/es/mutual-transport-layer-security.md
content/es/platform-as-a-service.md
content/es/virtualization.md

<s>Before merging this PR, we should merge first https://github.com/cncf/glossary/pull/3221 to update our `dev-es` branch and then, submit these changes to `main` branch.</s>
<s>Merge first https://github.com/cncf/glossary/pull/3229 to include the new term and content updated.</s>
<s>Merge first https://github.com/cncf/glossary/pull/3231 to include `dev-es` branch to main and include the latest changes.</s>
- Contributes to https://github.com/cncf/glossary/issues/3190
- Normalizes links, adding a trailing slash, as reported by the link checker
https://github.com/cncf/glossary/issues/3190
- [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: …

[es] Enable link checking and normalize links

---

.github/settings.yml
CODEOWNERS

This commit will add Asem Hamid as codeowners for the Bengali CNCF glossary.
Tracking Issue: https://github.com/cncf/glossary/issues/410

Adding asem hamid as  CODEOWNERS for Bengali

---

content/en/serverless.md

Hello, I'm updating the French translation of this term and I noticed 2 little problems with the links:
* Line 12: a page about OCI runtime exist, it would be nice to link it.
* Line 17: Both links are dead as PaaS and SaaS are deprecated terms. I thought deprecated terms were still accessible by direct links, but it gives a "Oops, this page doesn't exist" in the English version.  So I removed the links.
Thank you
This is a minor fix, so I didn't open an issue. Tell me if I need to open one.   …

[EN] Update `Serverless` - fix links

---

content/en/horizontal-scaling.md

Fixing the wrong statement that adding 4 x 4GB RAM nodes to a system of 4GB RAM will result in having 16GB RAM (it'll be 20GB then). I'm also removing a link to the Nodes article since this word was already linked in the previous paragraph.

[en] Small fix for horizontal-scaling.md

---

layouts/partials/head.html
package.json

- Update some dependencies
ref. #3189 

Update some dependencies

---

content/fr/devops.md

Suite à la revue du PR de tag-app-delivery https://github.com/cncf/tag-app-delivery/pull/693, passage aux pluriels comme dans la version anglais.
N/A

[FR] Update devops

---

content/en/function-as-a-service.md

Removed link to PaaS as it is a deprecated term. 
Removed useless spaces on line 26 
Added a new line at the end of line 28
I noticed that while localizing FaaS to French in https://github.com/cncf/glossary/pull/3297

[EN] update FaaS

---

content/en/stateless-apps.md

Simplified the definition Stateless applications.
Tried to make it easier  for beginners to understand

[EN] Update Stateless Apps

---

content/fr/serverless.md

FaaS and serverless were updated by this PR: https://github.com/cncf/glossary/pull/2217
We need to reflect these changes
Resolves https://github.com/cncf/glossary/issues/3236

[FR] update Serverless

---

content/es/.wordlist.txt
content/es/style-guide/_index.md

added the sign language video style guide (lang/es)
related to issue https://github.com/cncf/glossary/issues/3044#issue-2239321408

Add Sign Language Video Style Guide (SPA) to content/es/style-guide/index.md

---

layouts/partials/sidebar-tree.html

Due to the length of the sidebar content, it was commented that finding the next/previous pages in the sidebar was difficult (see #3209). This PR keeps the current active item in view in the sidebar, so navigating should be easier.
Preview: 
https://github.com/user-attachments/assets/7255dabc-a332-40a9-b592-6de3d0c63f59
Resolves #3209 

Scroll into view sidebar

---

package.json

- Updates all NPM packages except for Hugo, which will need to be addressed separately
- Updates the required Node version to match the [currently active LTS](https://nodejs.org/en/about/previous-releases). (It should also correspond to the Node version required by Docsy, but doesn't atm.)
- There are no changes to the generated site files as a result of these changes.
/cc @nate-double-u

Update packages and required Node version

---

content/fr/bare-metal-machine.md
content/fr/chaos-engineering.md
content/fr/client-server-architecture.md
content/fr/cloud-computing.md
content/fr/cloud-native-security.md
content/fr/container-orchestration.md
content/fr/continuous-delivery.md
content/fr/continuous-deployment.md
content/fr/continuous-integration.md
content/fr/distributed-apps.md
content/fr/edge-computing.md
content/fr/event-driven-architecture.md
content/fr/loosely-coupled-architecture.md
content/fr/microservices-architecture.md
content/fr/monolithic-apps.md
content/fr/multitenancy.md
content/fr/scalability.md
content/fr/service-discovery.md
content/fr/service-mesh.md
content/fr/shift-left.md
content/fr/stateful-apps.md
content/fr/stateless-apps.md
content/fr/tightly-coupled-architecture.md
content/fr/vertical-scaling.md
content/fr/virtual-machine.md
content/fr/zero-trust-architecture.md

[FR] fix capitalization

---

content/fr/webassembly.md

add webassembly in french
solves https://github.com/cncf/glossary/issues/3319

[FR] add webassembly

---

content/en/_index.md

- For context, see https://github.com/cncf/techdocs/pull/300
- Uses slack.cncf.io instead of communityinviter.com/apps/cloud-native/cncf
- Other minor copyedit.
/cc @nate-double-u

[editorial] Use slack.cncf.io as canonical URL

---

.github/settings.yml
CODEOWNERS

Remove localization maintainer (edsoncelio)
N/A
- [ x I have signed off on all commits 

feat: remove localization maintainer (edsoncelio)

---

config.toml
content/vi/_index.md
content/vi/contribute/_index.md
content/vi/style-guide/_index.md
i18n/vi.toml

This PR is to initiate Vietnamese localization based on
- Issue to #3458 
- https://github.com/cncf/glossary/blob/main/LOCALIZATION.md guide
Base and target branch of this PR is dev-vi which is development branch for Vietnamese localization.
This PR includes
- `[languages.vi]` section in `config.toml`
- content/**vi**/ directory
- i18n/vi.toml
- Some translated documents
- Main page
- content/vi/_index.md
- Others
- contribute: content/vi/contribute/_index.md (partially localized)
- style-guide: content/vi/style-guide/_index.md (partially localized)
Since Vietnamese localization team owns content/vi/* only,
this PR will require approvals from upstream owners (maintainers).

Settings and initial contents for Vietnamese localization

---

content/en/gitops.md

Updated an existing term - GitOps
Resolves https://github.com/cncf/glossary/issues/2073 and https://github.com/cncf/glossary/issues/372

[EN] update GitOps

---

content/es/abstraction.md
content/es/application-programming-interface.md
content/es/client-server-architecture.md
content/es/cloud-computing.md
content/es/cloud-native-apps.md
content/es/cloud-native-tech.md
content/es/cluster.md
content/es/container.md
content/es/data-center.md
content/es/kubernetes.md
content/es/loosely-coupled-architecture.md
content/es/microservices-architecture.md
content/es/monolithic-apps.md
content/es/nodes.md
content/es/platform-as-a-service.md
content/es/pod.md
content/es/portability.md
content/es/reliability.md
content/es/scalability.md
content/es/service.md
content/es/software-as-a-service.md
content/es/stateful-apps.md
content/es/stateless-apps.md
content/es/style-guide/_index.md
content/es/tightly-coupled-architectures.md
content/es/virtual-machine.md
content/es/virtualization.md

Finds all occurrences of `Fundamental`, `Fundamento` or `Fundamentos` and replaces it with `Básico` as it's the Spanish equivalent. ~It also applies some format fixes like trailing spaces and bad tabulations.~
Resolves #3437

fix: rename tag to Fundamentos

---

CODEOWNERS

@thaomike
PR's
- #3469 
- #3477
- #3481

REQUEST: new /vi approver for @thaomike

---

content/it/abstraction.md

IT localization,Abstraction update: tag addedd, service link corrected to it localization,identation improved.
#3083 

[it]Abstraction IT,aggiunti tag, aggiornato link,corretta identazione  #3083

---

content/en/contribute/_index.md

update before you start section to remove obsolete information and include info about signing commits.
see #2017 

Update Contribution Guide

---

content/vi/_index.md
content/vi/auto-scaling.md
content/vi/cluster.md
content/vi/continuous-delivery.md
content/vi/continuous-deployment.md
content/vi/continuous-integration.md
content/vi/immutable-infrastructure.md
content/vi/infrastructure-as-a-service.md
content/vi/infrastructure-as-code.md
content/vi/loosely-coupled-architecture.md
content/vi/platform-as-a-service.md
content/vi/policy-as-code.md
content/vi/stateful-apps.md
content/vi/stateless-apps.md
content/vi/zero-trust-architecture.md

Merge Vietnamese development branch into main.

Merge dev-vi into main

---

content/tr/runtime.md

Add Turkish translation for Runtime glossary term

---

content/tr/serverless.md

Add Turkish localization for Serverless

---

content/vi/multitenancy.md

Add translation for Multitenancy

[vi] Add translation for Multitenancy
